"""風場卡片的照片清單 · Photos for the globe's cards（tools/build_photos.py 讀這個檔）

每一張都人工看過才列進來：
- 照片要看得到這座風場（或這部里程碑風機）的風機，不是地圖、標誌、典禮人群、只拍船或零件、或風機小到看不清的風景；
- 出自該風場自己的 Commons 分類；沒有風場分類時，檔名或說明要寫明是這座風場（例如台電網站的「○○風力發電站」照片）。第 4 欄寫照片所在的分類，建置會檢查；
- 授權是 CC0／公有領域／CC BY／CC BY-SA，或 Commons 的 Attribution（只要求標示來源，台灣政府開放資料多用這個；建置會檢查）；
- 最後一欄寫看到什麼，方便之後複查。找候選用 `python3 tools/find_photos.py 風場名稱 --save 目錄`。
事件只放拍到該事件本身的照片；沒有的話卡片會改用相關風場的照片，並註明不是事件當時。

Every photo here was looked at by hand: it shows this farm's (or milestone machine's) turbines rather than a map, logo,
ceremony crowd, vessel, component or distant scenery; it comes from the farm's own Commons category or, where there is none, its
title or description names the farm (column 4 is the category the file sits in, checked by the build); the licence is CC0 / public
domain / CC BY / CC BY-SA or Commons' Attribution (checked by the build); the last column says what the photo shows.
Event photos must show the event itself; otherwise the card uses a related farm's photo and says it is not of the event.
"""

# (國別, 風場名稱（與 wind_farms.json 完全一致）, Commons 檔名, Commons 分類, 照片內容)
FARMS = [
    ('TWN', 'Formosa 1 Phase 1', 'File:05.05 5+2產業創新系列行程-總統參訪「海洋風電公司離岸風機」 (41003819985).jpg',
     'Category:Wind turbines in Taiwan', '2018-05-05 從岸邊看海洋風電的 2 部示範機（當時只有這 2 部），檔名寫明海洋風電公司離岸風機'),
    ('TWN', 'Formosa 1 Phase 2', 'File:11.12 總統出席「海洋離岸風場」啟動典禮 (49053127786).jpg',
     'Category:Formosa 1 Offshore Wind Farm', '2019-11-12 啟用典禮時拍的 5 部離岸風機（黃色轉接段），沒有人物'),
    ('TWN', 'Taipower Offshore Phase 1 (Changhua)', 'File:台電離岸風力發電場 第一期.jpg',
     'Category:Offshore wind farms in Taiwan', '空拍：近處一部、遠處數部離岸風機與工作船；檔名寫明台電離岸第一期'),
    ('TWN', 'Formosa 2', 'File:海能離岸風力發電場.jpg',
     'Category:Offshore wind farms in Taiwan', '空拍完工的海能風場：前景一部黃色套管式基礎風機、遠處約 8 部'),
    ('TWN', 'Taichung Port', 'File:台中港風力發電站.jpg',
     'Category:Taichung Port Wind Farm', '高美濕地海堤上一長排風機與潮間帶倒影，藍天'),
    ('TWN', 'Taichung Power Plant', 'File:台中電廠風力發電站.jpg',
     'Category:Wind turbines in Taiwan', '台中電廠廠區旁的風機（台電網站照片，浮水印「台中電廠風力發電」）'),
    ('TWN', 'Shimen', 'File:Wongwt 石門風力發電廠 (16606778654).jpg',
     'Category:Shimen Wind Farm', '石門海岬上的紅白相間風機，近處一部、木棧道後方四部'),
    ('TWN', 'Penghu Zhongtun', 'File:中屯風力發電站.jpg',
     'Category:Wind farms in Taiwan', '中屯的白色風機與花叢（台電網站照片；風場已於 2025 年拆除）'),
    ('TWN', 'Yunmai (Mailiao)', 'File:雲麥風力發電站.jpg',
     'Category:Wind farms in Taiwan', '雲麥（麥寮）沿海防風林上的一排風機（台電網站照片）'),
    ('TWN', 'Dayuan Guanyuan', 'File:觀園風力發電站.jpg',
     'Category:Wind farms in Taiwan', '觀園海岸沙丘上的一排風機（台電網站照片）'),
    ('TWN', 'Guanyin', 'File:觀威觀音風力發電站.jpg',
     'Category:Wind turbines in Taiwan', '一部風機特寫；說明寫明達德能源觀威觀音風力發電站'),
    ('TWN', 'Changgong (Changbin Xianxi)', 'File:彰工風力發電站.png',
     'Category:Wind farms in Taiwan', '空拍海堤道路旁的一部風機與影子；說明寫明台電彰工風力發電站'),
    ('TWN', 'Datan (Tatan)', 'File:大潭風力發電站.jpg',
     'Category:Wind farms in Taiwan', '海堤旁的兩部風機（台電網站照片）'),
    ('TWN', 'Linkou', 'File:林口風力發電站.jpg',
     'Category:Wind farms in Taiwan', '林口海岸夕陽下的三部風機（台電網站照片）'),
    ('TWN', 'Hengchun (Maanshan NPP)', 'File:恆春風力發電站.jpg',
     'Category:Wind farms in Taiwan', '核三廠旁海岬上的兩部風機（台電網站照片）'),
    ('TWN', 'Penghu Huxi', 'File:Huxi Windpower Plant.jpg',
     'Category:Huxi Windpower Plant', '澎湖湖西草原上的四部風機'),
    ('TWN', 'Penghu Longmen', 'File:澎湖龍門風力發電站 02.jpg',
     'Category:Longmen Wind Farm', '步道旁一部風機、遠處另一部'),
    ('TWN', 'Dapeng (Miaoli Houlong)', 'File:Wind Farm - panoramio (8).jpg',
     'Category:Dapeng Wind Farm', '後龍海岸丘陵上的四部風機'),
    ('TWN', 'Wanggong', 'File:彰化縣芳苑鄉 王功漁港 風力發電風車 - panoramio.jpg',
     'Category:Wanggong Wind Farm', '王功海堤上的五、六部風機'),
    ('TWN', 'Hsinchu Xiangshan', 'File:香山風力發電站.jpg',
     'Category:Wind turbines in Taiwan', '樹林上方的一部風機；檔名寫明香山風力發電站'),
    ('TWN', 'Kinmen Jinsha', 'File:金沙風力發電站.jpg',
     'Category:Wind turbines in Taiwan', '海灣上方的一部風機（台電網站照片）'),
    ('DNK', 'Middelgrunden', 'File:Boattrip 2009.jpg',
     'Category:Middelgrunden offshore wind farm', '船上看 Middelgrunden 的弧形風機列'),
    ('DNK', 'Horns Rev 1', 'File:Horns Rev 1 offshore wind farm.jpg',
     'Category:Horns Rev 1 offshore wind farm', '海平線上的 Horns Rev 1 風機群（較遠）'),
    ('DNK', 'Anholt', 'File:Anholt Havmøllepark.jpg',
     'Category:Anholt Offshore Wind Farm', 'Anholt 離岸風場的風機列'),
    ('DEU', 'alpha ventus', 'File:2012-05-13 Nordsee-Luftbilder DSCF8885.jpg',
     'Category:Alpha ventus', '空拍 alpha ventus 的風機與套管式基礎'),
    ('DEU', 'BARD Offshore 1', 'File:Bard Offshore 2011.JPG',
     'Category:Bard 1 offshore wind farm', 'BARD Offshore 1 的三腳樁基礎風機'),
    ('GBR', 'London Array', 'File:London Array Wind Farm in the Thames Estuary - geograph.org.uk - 7226633.jpg',
     'Category:London Array offshore wind farm', '泰晤士河口的 London Array 風機群'),
    ('GBR', 'Walney Extension', 'File:Turbine, Walney Offshore Windfarm - geograph.org.uk - 5496317.jpg',
     'Category:Walney Wind Farm', '一部風機近景；geograph 說明寫明是 Walney 擴建風場'),
    ('GBR', 'Blyth Offshore', 'File:Fishermen and wind turbines from Blyth North Beach - geograph.org.uk - 1133638.jpg',
     'Category:Blyth Offshore Wind Farm', '2004 年從 Blyth 北灘看原本的 2 部 V66，前景有釣客'),
    ('BEL', 'Thornton Bank II', 'File:CP-A4.jpg',
     'Category:Thornton Bank wind farm', '一部套管式基礎風機；說明寫明是第二期'),
    ('USA', 'Block Island', 'File:Block Island offshore wind farm P6290638m.jpg',
     'Category:Block Island Wind Farm', 'Block Island 的套管式基礎風機'),
    # 2026-10-06 新增（逐張看過；日期、說明與分類都向 Commons 查過）
    ('GBR', 'Gwynt y Môr', 'File:Gwynt y Môr offshore wind farm located off the coast of Wales from Rhiwledyn (Little Orm), Wales 11.jpg',
     'Category:Gwynt y Môr offshore wind farm', '2017-03 從小奧姆角以長鏡頭拍：近處一部黃色轉接段的風機，後方一整排風機'),
    ('GBR', 'Burbo Bank', 'File:Burbo Bank Offshore Wind Farm - geograph.org.uk - 4655370.jpg',
     'Category:Burbo Bank Offshore Wind Farm', '2015-09 從岸邊看約 9 部黃色轉接段的風機（擴建案 2016 年才開工，所以是原本的 Burbo Bank）'),
    ('GBR', 'Robin Rigg', 'File:Robin Rigg Wind Farm (geograph 2583753).jpg',
     'Category:Robin Rigg Wind Farm', '2011-08 索爾威灣上一排黃色基座的風機，背後是山'),
    ('GBR', 'Sheringham Shoal', 'File:Sheringham Shoal Wind Farm - geograph.org.uk - 4608752.jpg',
     'Category:Sheringham Shoal Wind Farm', '2015-08 海平線上 5 部風機'),
    ('DNK', 'Nysted (Rødsand I)', 'File:Windpark Nysted.jpg',
     'Category:Nysted Wind Farm', '2008-04 空拍：Nysted 方格狀排列的風機'),
    ('DNK', 'Rødsand II', 'File:Rødsand I and II (crop).jpg',
     'Category:Nysted Wind Farm', '2011-06 空拍：前景是 Rødsand II 的弧形風機列（說明寫明 II 在前景、I 在背景）'),
    ('BEL', 'Belwind I (Bligh Bank)', 'File:Belwind.jpg',
     'Category:Belwind wind farm', '2012-10 海上看 Bligh Bank 上的 Belwind：數部黃色轉接段的風機'),
    ('DEU', 'Arkona', 'File:OWP Arkona 5028.jpg',
     'Category:Arkona offshore wind farm', '2018-09 從博恩霍爾姆渡輪看 Arkona：近處一部黃色轉接段的單樁風機，後方多部（鄰近的 Wikinger 是套管式，不是它）'),
    ('IND', 'Jaisalmer Wind Park', 'File:A Wind Energy farm and the Cenotaphs, the ancient and the modern, Jaisalmer Rajasthan India.jpg',
     'Category:Jaisalmer Wind Park', '2012-10 巴達巴格衣冠塚群後方的風機（近處一部、遠處多部）'),
    ('USA', 'Roscoe', 'File:Roscoe Wind Farm in West Texas.jpg',
     'Category:Roscoe Wind Farm', '2014-10 田地後方的多部風機與一座舊式抽水風車'),
    ('CHN', 'Donghai Bridge', 'File:Donghai Bridge Wind Farm.jpg',
     'Category:Donghai Bridge Wind Farm', '東海大橋旁的離岸風機'),
    ('CHN', 'Gansu Guazhou / Jiuquan wind base', 'File:Guazhou.champs éoliennes.jpg',
     'Category:Guazhou wind farm', '瓜州戈壁上大片風機與輸電塔'),
    ('NOR', 'Hywind Demo (Karmøy)', 'File:Hywind havvindmølle.JPG',
     'Category:Floating wind turbines', '空拍 Hywind 浮動風機（2009 年 5 月組裝中、拖到 Karmøy 外海前），旁邊是工作駁船'),
    ('PRT', 'WindFloat 1 (Aguçadoura demo)', 'File:Agucadoura WindFloat Prototype.jpg',
     'Category:Aguçadoura', '空拍 WindFloat 半潛式浮台與風機'),
    ('PRT', 'WindFloat Atlantic', 'File:Central Offshore Windfloat Atlantic - Portugal (53426345383).jpg',
     'Category:Offshore wind farms in Portugal', '海平線上的三部浮動風機與黃色浮台；檔名寫明 WindFloat Atlantic'),
    ('GBR', 'Hywind Scotland', 'File:Hywind Wind Farm, off Peterhead - geograph.org.uk - 7226685.jpg',
     'Category:Floating wind turbines', '黃昏時 Peterhead 外海的兩部 Hywind 風機；檔名寫明'),
    ('FRA', 'Floatgen (SEM-REV)', 'File:Eolienne flottante FLOATGEN (Ifremer 00698-81047 - 33096).jpg',
     'Category:FLOATGEN', 'Floatgen 浮動風機與環形浮台'),
    ('JPN', 'Akita Port', 'File:Offshore wind turbines at the Port of Akita 20221025.jpg',
     'Category:Offshore wind farm at the Port of Akita', '秋田港的離岸風機'),
    ('JPN', 'Noshiro Port', 'File:Offshore wind turbines at the Port of Noshiro 20230826.jpg',
     'Category:Offshore wind farm at the Port of Noshiro', '能代港的離岸風機'),
]

# (里程碑名稱（與 wind_global.json 完全一致）, Commons 檔名, Commons 分類, 照片內容)
MILESTONES = [
    ('Brush wind turbine, Cleveland', 'File:Wind turbine 1888 Charles Brush.jpg',
     'Category:Charles F. Brush', '1888 年 Brush 的大型風車（歷史照片，公有領域）'),
    ("Smith–Putnam turbine, Grandpa's Knob, Vermont", 'File:Wind turbine 1941.jpg',
     'Category:Wind turbines in Vermont', '1941 年 Smith–Putnam 兩葉風機的鋼架塔（歷史照片，公有領域）'),
    ('Gedser wind turbine', 'File:Gedsermøllens vinger.jpg',
     'Category:Gedsermøllen', 'Gedser 風機原本的轉子與機艙，現展示在丹麥電力博物館（不在塔上）'),
    ('NASA/DOE MOD-0, Plum Brook Station, Ohio', 'File:A 100-kilowatt wind turbine (16140843960).jpg',
     'Category:MOD-0 research wind turbine in Sandusky, Ohio', 'NASA MOD-0 100 kW 試驗風機（公有領域）'),
    ('Tvind turbine (Tvindkraft), Ulfborg', 'File:Tvindmøllen.jpg',
     'Category:Tvindkraft', 'Tvind 風機仰視'),
    ('NASA/DOE MOD-1, Boone, North Carolina', 'File:MOD-1 WIND TURBINE IN BOONE NORTH CAROLINA - DPLA - b5c05d9b152f5664792dd0f5d1106203.jpg',
     'Category:MOD-1 wind turbine in Boone, North Carolina', 'Boone 的 MOD-1 風機（公有領域）'),
    ('NASA/DOE MOD-2 cluster, Goodnoe Hills, Washington', 'File:Mod-2 Wind Turbine Cluster3.jpg',
     'Category:MOD-2 research wind turbines in Goodnoe Hills, Washington', 'Goodnoe Hills 的 MOD-2 風機群（公有領域）'),
    ('Altamont Pass wind farm, California', 'File:Altamont Pass Wind Farm.jpg',
     'Category:Altamont Pass Wind Farm', 'Altamont Pass 山丘上的風機（近年照片）'),
    ('Growian, Kaiser-Wilhelm-Koog', 'File:Growian001.png',
     'Category:Growian', 'Growian 兩葉大型風機'),
    ('Muppandal wind farm (first phase), Tamil Nadu', 'File:Wind Farm Muppandal.jpg',
     'Category:Muppandal Wind Farm', 'Muppandal 風場（近年照片）'),
    ('Delabole wind farm, Cornwall', 'File:The Delabole wind farm - geograph.org.uk - 216985.jpg',
     'Category:Delabole Wind Farm', '約 2006 年、2010 年汰換前的 Delabole 風機'),
    ('Enercon E-66 (first units), Emden / Aurich', 'File:WEAEnerconWybelsum retouched.jpg',
     'Category:Enercon E-66', 'Emden Wybelsumer Polder 的一部 Enercon E-66（不是第一批機組）'),
    ('Enercon E-126, Emden (Rysumer Nacken)', 'File:2008-08-04 1 Windpark Rysumer Nacken 005.JPG',
     'Category:Enercon E-126', '2008 年 Emden Rysumer Nacken 的 Enercon E-126'),
    ('Dabancheng wind farm, Xinjiang', 'File:新疆-达板城风力发电机组 - panoramio.jpg',
     'Category:Dabancheng District', '達坂城戈壁上的大片風機（有日光眩光）；檔名寫明達坂城'),
    ('Jiuquan (Gansu) Wind Power Base', 'File:Guazhou.champs éoliennes.jpg',
     'Category:Guazhou wind farm', '瓜州（酒泉基地的一部分）戈壁上的風機與輸電塔'),
    ('Donghai Bridge offshore wind farm, Shanghai', 'File:Donghai Bridge Wind Farm.jpg',
     'Category:Donghai Bridge Wind Farm', '東海大橋旁的離岸風機'),
    ('Hywind Demo, Karmøy', 'File:Hywind havvindmølle.JPG',
     'Category:Floating wind turbines', '空拍 Hywind 浮動風機（2009 年 5 月組裝中、拖到 Karmøy 外海前）'),
    ('Hywind Scotland, Buchan Deep', 'File:Hywind Wind Farm, off Peterhead - geograph.org.uk - 7226685.jpg',
     'Category:Floating wind turbines', '黃昏時 Peterhead 外海的兩部 Hywind 風機'),
]

# (事件代碼, Commons 檔名, Commons 分類, 照片內容)
EVENTS = [
    # 2026-10 查過薔蜜、蘇迪勒、梅姬、梅米颱風、摩羯颱風在中國的災情與 Hornslet 倒塔：Commons 沒有拍到風機受損的照片
]
