"""離岸風場水下基礎型式：逐場對照表（逐步收集；見 ROADMAP「使用者 2026-09 提出的新規劃」第 2 項）。

tools/build_foundations.py 讀這張表，產生 data/global/foundations.json（地球儀的「水下基礎」圖層）與
docs/foundations.md、docs/foundations.en.md。

每一列用（國別, 風場名稱）指定 wind_farms.json 裡剛好一座離岸或浮動式風場，名稱要完全一致。
    t      型式代碼（見 TYPES）；混合型用 'mx'，並在 parts 列出各型式的座數
    ospar  對應的 OSPAR Offshore Renewables 2024 紀錄（data/global/sources/ospar_offshore_renewables_2024.csv）
    url    第二來源：OSPAR 沒有具體型式、或與實際建成的不同時必填，並在 zh／en 說明
    sub    細分型式（吸力桶、單柱式…，見 SUBS）
    zh/en  顯示在風場卡片的註記
建置時會檢查：風場存在且是離岸或浮動式；引用 OSPAR 時，OSPAR 的值要與 t 相符，不相符（或 OSPAR 沒有具體型式）就必須
有 url 與理由；同一座風場不可出現兩次。

第 1 步（2026-09，F）：OSPAR 涵蓋的北海與東北大西洋。OSPAR 的「營運中」紀錄逐筆比對過名稱、位置與容量；
德國的紀錄不可靠（10 筆只寫「單樁／三腳／三樁／套管／重力式／其他」任一種，Merkur、Veja Mate、Trianel Borkum II 與
alpha ventus 則與建成紀錄不符），所以德國每一座都改以德文維基百科資訊框的「Gründung」（附建造紀錄）為準；
Hornsea One 西區也與建成紀錄不符。
第 2 步（2026-09，F2）：歐洲其他風場，包括 OSPAR 範圍以外的波羅的海、地中海與艾瑟爾湖，以及 OSPAR 2024 之後才完工的風場。
每一座都附出處（開發商、施工廠商、產業新聞、政府文件或維基百科，原文逐筆核對過）。OSPAR 對 2024 年以後完工的風場只有
核准階段的設計（Current Status 是 authorised 等，不是 operational 或 decommissioned），設計可能改變，所以這種紀錄一定要再附施工紀錄，建置會檢查。
第 3 步（2026-09，F3）：全球的浮動式風場補上細分型式（單柱式、半潛式、駁船式、張力腳），逐座查技術供應商與開發商資料。
浮動式的列一定要有細分型式；同一筆紀錄含不同型式的機組時（例：福島的示範機組），以中英文說明代替，建置會檢查。
第 4 步（2026-09，F4）：台灣、日本、韓國、美國的離岸風場。這些海域沒有 OSPAR 紀錄，每一座都附開發商、施工廠商、政府文件或
產業新聞的出處，引用的原文逐筆核對過（tools/check_quotes.py），不引用 4C Offshore。日本港灣內的風場以 NEDO 的支持構造分類為準
（NEDO 明寫「ドルフィン」＝ High-Rise Pile Cap 高樁承台）。
第 5 步（2026-09 起，F5）：中國、越南。先依使用者 2026-09-27 整理的《全球離岸風場資料庫｜亞洲查核版 v2》「亞洲逐案覆核」
補上中國 4 座與中廣核如東 H8，2026-09-30 起逐批補查（開發商、施工廠商、地方政府公開的海域使用論證報告與竣工環保驗收、產業新聞），
引用的原文都以 tools/check_quotes.py 核對過；只有如東 H6、H10 的出處是三峽集團自家網頁，核對環境連不上（見 TODO）。
沒把握的不列（見 EXCLUDED），不臆測。
"""

ASOF = '2026-09'
OSPAR_URL = 'https://odims.ospar.org/en/submissions/ospar_offshore_renewables_2024_01/'
DE = 'https://de.wikipedia.org/wiki/'
EN = 'https://en.wikipedia.org/wiki/'
FR = 'https://fr.wikipedia.org/wiki/'

# 型式：代碼 → (中文, English, 地圖色組)。地圖上多於三種色相時分不清（見 globe.js 的 FD_GROUPS），
# 所以依結構歸成四組：單樁、鋼構框架（套管、三腳、三樁）、浮動式、其他固定式（重力式、高樁承台、圍堰式、岩錨式、複合筒、混合）。
# 圍堰式：近岸淺水處用鋼板樁（或鋼管樁加板樁）圍成一圈、填砂，上面做混凝土基座，等於把陸上風機的基礎做在水中
# 岩錨式：湖底或海底是岩盤時，以錨桿把基礎固定在岩盤上
# 複合筒：大直徑鋼筒（頂部為混凝土或鋼構過渡段，後者中廣核稱「全鋼筒型」）以負壓沉入海床，靠筒體與土壤承載；中國江蘇等軟弱海床常用，不打樁
TYPES = {
    'mp': ('單樁', 'Monopile', 'mp'),
    'jk': ('套管式', 'Jacket', 'frame'),
    'tp': ('三腳架', 'Tripod', 'frame'),
    'tl': ('三樁', 'Tripile', 'frame'),
    'gb': ('重力式', 'Gravity-based', 'other'),
    'pc': ('高樁承台', 'High-rise pile cap', 'other'),
    'cf': ('圍堰式', 'Cofferdam', 'other'),
    'ra': ('岩錨式', 'Rock-anchored', 'other'),
    'bk': ('複合筒', 'Composite bucket', 'other'),
    'mx': ('混合', 'Mixed', 'other'),
    'fl': ('浮動式', 'Floating', 'fl'),
}
SUBS = {
    'sb': ('吸力桶', 'suction bucket'),
    'spar': ('單柱式', 'spar'),
    'semi': ('半潛式', 'semi-submersible'),
    'barge': ('駁船式', 'barge'),
    'tlp': ('張力腳', 'tension-leg platform'),
}


def F(iso, name, t, ospar=(), url=None, sub=None, parts=None, zh='', en='', step=1):
    return dict(iso=iso, name=name, t=t, ospar=list(ospar), url=url, sub=sub, parts=parts, zh=zh, en=en, step=step)


def F2(*a, **k):
    """第 2 步加入的列"""
    return F(*a, step=2, **k)


def F3(*a, **k):
    """第 3 步加入的列（浮動式）"""
    return F(*a, step=3, **k)


def F4(*a, **k):
    """第 4 步加入的列（台灣、日本、韓國、美國）"""
    return F(*a, step=4, **k)


def F5(*a, **k):
    """第 5 步加入的列（中國、越南）"""
    return F(*a, step=5, **k)


FLOAT_SUBS = ('spar', 'semi', 'barge', 'tlp')      # 浮動式的細分型式（sb 吸力桶是固定式套管用的）


GER = ('OSPAR 只寫「任一種」，改以德文維基百科（附建造紀錄）為準', 'OSPAR says “any of these”, so German Wikipedia (with construction records) is used')

FOUNDATIONS = [
    # ------------------------------------------------ Belgium
    F('BEL', 'Belwind I (Bligh Bank)', 'mp', ['Be003']),
    F('BEL', 'Nobelwind (Bligh Bank II)', 'mp', ['Be009']),
    F('BEL', 'Thornton Bank I', 'gb', ['Be001'], EN + 'Thorntonbank_Wind_Farm',
      zh='第一期 6 部風機坐在混凝土重力式基礎上；OSPAR 把三期合成一筆「重力式／套管」',
      en='The six phase-1 turbines stand on concrete gravity bases; OSPAR lists the three phases together as “gravity-based/jacket”'),
    F('BEL', 'Thornton Bank II', 'jk', ['Be001'], EN + 'Thorntonbank_Wind_Farm',
      zh='第二、三期共 48 部風機用鋼製套管基礎（OWEC 設計）', en='Phases 2 and 3 (48 turbines) use steel jackets designed by OWEC'),
    F('BEL', 'Thornton Bank III', 'jk', ['Be001'], EN + 'Thorntonbank_Wind_Farm',
      zh='第二、三期共 48 部風機用鋼製套管基礎（OWEC 設計）', en='Phases 2 and 3 (48 turbines) use steel jackets designed by OWEC'),
    F('BEL', 'Norther', 'mp', ['Be005']),
    F('BEL', 'Northwester 2', 'mp', ['Be008']),
    F('BEL', 'Northwind', 'mp', ['Be002']),
    F('BEL', 'Rentel', 'mp', ['Be004']),
    F('BEL', 'SeaMade - Mermaid', 'mp', ['Be007']),
    F('BEL', 'SeaMade - Seastar', 'mp', ['Be006']),
    # ------------------------------------------------ Denmark（北海與卡特加特海峽；波羅的海不在 OSPAR 範圍）
    F('DNK', 'Horns Rev 1', 'mp', ['DK02']),
    F('DNK', 'Horns Rev 2', 'mp', ['DK05']),
    F('DNK', 'Horns Rev 3', 'mp', ['DK24']),
    F('DNK', 'Rønland', 'gb', ['DK04']),
    F('DNK', 'Nissum Bredning Vind', 'jk', ['DK23'], 'https://m.aarsleff.dk/img/8088/0/0/Download/253-nissum-bredning-dk',
      zh='4 座三腳鋼套管，各以 3 支直徑 1.45 m、長 75 m 的打入斜樁固定，上加約 1,200 噸的混凝土轉接段（安裝商 Aarsleff）；西門子稱為「重力式套管」，OSPAR 寫重力式應是因為沉重的混凝土轉接段',
      en='Four three-legged steel jackets, each held by three driven raked piles 1.45 m across and 75 m long, topped by a concrete transition piece of about 1,200 t (installer Aarsleff); Siemens called it a “gravity jacket”, which is presumably why OSPAR says gravity-based'),
    F('DNK', 'Anholt', 'mp', ['DK14']),
    F('DNK', 'Vesterhav Syd', 'mp', ['DK26']),
    F('DNK', 'Vesterhav Nord', 'mp', ['DK27']),
    # ------------------------------------------------ France
    F('FRA', 'Saint-Nazaire (Banc de Guérande)', 'mp', ['FR03'], FR + 'Parc_%C3%A9olien_en_mer_de_Saint-Nazaire'),
    F('FRA', 'Saint-Brieuc', 'jk', ['FR02']),
    F('FRA', 'Fécamp', 'gb', ['FR04'], FR + 'Parc_%C3%A9olien_en_mer_de_F%C3%A9camp',
      zh='71 座混凝土重力式基礎（每座約 5,000 噸）', en='71 concrete gravity bases (about 5,000 t each)'),
    F('FRA', 'Provence Grand Large', 'fl', ['FR11'], 'https://www.edf.fr/en/the-edf-group/dedicated-sections/journalists/all-press-releases/provence-grand-large-full-commissioning-of-the-first-french-floating-offshore-wind-farm',
      sub='tlp', zh='SBM Offshore 與 IFPEN 開發的張力腳平台（細分型式於第 3 步補上）',
      en='Tension-leg platforms developed by SBM Offshore and IFPEN (sub-type added in step 3)'),
    # ------------------------------------------------ Germany（北海；每一座以德文維基百科為準）
    F('DEU', 'alpha ventus', 'mx', ['DE001'], DE + 'Offshore-Windpark_alpha_ventus', parts=[['tp', 6], ['jk', 6]],
      zh='6 部三腳架、6 部套管；OSPAR 誤列為「單樁／套管」', en='6 tripods and 6 jackets; OSPAR wrongly lists “monopile/jacket”'),
    F('DEU', 'DanTysk', 'mp', ['DE002'], DE + 'Offshore-Windpark_DanTysk'),
    F('DEU', 'Borkum Riffgrund 1', 'mp', ['DE004'], DE + 'Offshore-Windpark_Borkum_Riffgrund',
      zh='77 座單樁，另有 1 座吸力桶套管（試驗）', en='77 monopiles plus one suction-bucket jacket (a trial)'),
    F('DEU', 'Borkum Riffgrund 2', 'mx', ['DE028'], DE + 'Offshore-Windpark_Borkum_Riffgrund', parts=[['mp', 36], ['jk', 20]], sub='sb',
      zh='36 座單樁、20 座吸力桶套管', en='36 monopiles and 20 suction-bucket jackets'),
    F('DEU', 'Amrumbank West', 'mp', ['DE005'], DE + 'Offshore-Windpark_Amrumbank_West', zh=GER[0], en=GER[1]),
    F('DEU', 'Nordsee Ost', 'jk', ['DE006'], DE + 'Offshore-Windpark_Nordsee_Ost'),
    F('DEU', 'Butendiek', 'mp', ['DE008'], DE + 'Offshore-Windpark_Butendiek'),
    F('DEU', 'Global Tech I', 'tp', ['DE009'], DE + 'Offshore-Windpark_Global_Tech_I'),
    F('DEU', 'Sandbank', 'mp', ['DE012'], DE + 'Offshore-Windpark_Sandbank', zh=GER[0], en=GER[1]),
    F('DEU', 'Gode Wind 1', 'mp', ['DE013'], DE + 'Offshore-Windpark_Gode_Wind_I', zh=GER[0], en=GER[1]),
    F('DEU', 'Gode Wind 2', 'mp', ['DE032'], DE + 'Offshore-Windpark_Gode_Wind_II'),
    F('DEU', 'Gode Wind 3', 'mp', ['DE074'], DE + 'Offshore-Windpark_Gode_Wind_III'),
    F('DEU', 'EnBW He Dreiht', 'mp', ['DE017'], DE + 'Offshore-Windpark_He_dreiht', zh=GER[0], en=GER[1]),
    F('DEU', 'Nordergründe', 'mp', ['DE018'], DE + 'Offshore-Windpark_Nordergr%C3%BCnde', zh=GER[0], en=GER[1]),
    F('DEU', 'Riffgat', 'mp', ['DE019'], DE + 'Offshore-Windpark_Riffgat', zh=GER[0], en=GER[1]),
    F('DEU', 'BARD Offshore 1', 'tl', ['DE021'], DE + 'BARD_Offshore_1'),
    F('DEU', 'Deutsche Bucht', 'mp', ['DE022'], DE + 'Offshore-Windpark_Deutsche_Bucht'),
    F('DEU', 'Merkur', 'mp', ['DE024'], DE + 'Offshore-Windpark_Merkur',
      zh='66 座單樁；OSPAR 列為三腳架，與建成紀錄不符', en='66 monopiles; OSPAR lists tripods, which does not match what was built'),
    F('DEU', 'Trianel Windpark Borkum I', 'tp', ['DE025a'], DE + 'Trianel_Windpark_Borkum'),
    F('DEU', 'Trianel Windpark Borkum II', 'mp', ['DE025b'], DE + 'Trianel_Windpark_Borkum',
      zh='第二期用單樁；OSPAR 列為三腳架／三樁', en='Phase 2 uses monopiles; OSPAR lists tripod/tripile'),
    F('DEU', 'Nordsee One', 'mp', ['DE026'], DE + 'Offshore-Windpark_Nordsee_One', zh=GER[0], en=GER[1]),
    F('DEU', 'Kaskasi', 'mp', ['DE031'], DE + 'Offshore-Windpark_Kaskasi'),
    F('DEU', 'Veja Mate', 'mp', ['DE034'], DE + 'Offshore-Windpark_Veja_Mate',
      zh='67 座單樁（直徑 7.8 m）；OSPAR 列為三腳架／三樁', en='67 monopiles (7.8 m diameter); OSPAR lists tripod/tripile'),
    F('DEU', 'Meerwind Süd/Ost', 'mp', ['DE036'], DE + 'Offshore-Windpark_Meerwind', zh=GER[0], en=GER[1]),
    F('DEU', 'Albatros', 'mp', ['DE037'], DE + 'Offshore-Windpark_Albatros', zh=GER[0], en=GER[1]),
    # ------------------------------------------------ Netherlands
    F('NLD', 'Egmond aan Zee (OWEZ)', 'mp', ['NL001']),
    F('NLD', 'Prinses Amalia', 'mp', ['NL002']),
    F('NLD', 'Luchterduinen', 'mp', ['NL003']),
    F('NLD', 'Gemini', 'mp', ['NL004']),
    F('NLD', 'Borssele I & II', 'mp', ['NL005']),
    F('NLD', 'Borssele III & IV (Blauwwind)', 'mp', ['NL006']),
    F('NLD', 'Hollandse Kust Zuid I & II', 'mp', ['NL007']),
    F('NLD', 'Hollandse Kust Zuid III & IV', 'mp', ['NL007']),
    F('NLD', 'Hollandse Kust Noord', 'mp', ['NL008']),
    # ------------------------------------------------ Norway
    F('NOR', 'Hywind Demo (Karmøy)', 'fl', ['NO001'], EN + 'Hywind', sub='spar',
      zh='2019 年起改名 Unitech Zefyros（OSPAR 用此名）', en='Renamed Unitech Zefyros in 2019 (the name OSPAR uses)'),
    F('NOR', 'Hywind Tampen', 'fl', ['NO010'], EN + 'Hywind_Tampen', sub='spar', zh='混凝土單柱式浮台', en='Concrete spar buoys'),
    F('NOR', 'TetraSpar Demonstrator (METCentre)', 'fl', ['NO018'], 'https://stiesdaloffshore.com/projects/the-tetraspar-full-scale-demonstration-project/',
      sub='spar', zh='Stiesdal 的 Tetra 浮台，採單柱式配置（下方懸吊壓艙）；2026 年除役（細分型式於第 3 步補上）',
      en='Stiesdal’s Tetra floater in a spar configuration (with a suspended keel); decommissioned in 2026 (sub-type added in step 3)'),
    # ------------------------------------------------ United Kingdom
    F('GBR', 'Barrow', 'mp', ['UK002']),
    F('GBR', 'Beatrice', 'jk', ['UK003']),
    F('GBR', 'Blyth Offshore', 'mp', ['UK007']),
    F('GBR', 'Blyth Offshore Demonstrator', 'gb', ['UK005']),
    F('GBR', 'Burbo Bank', 'mp', ['UK013']),
    F('GBR', 'Burbo Bank Extension', 'mp', ['UK012']),
    F('GBR', 'Dudgeon', 'mp', ['UK019']),
    F('GBR', 'East Anglia ONE', 'jk', ['UK022']),
    F('GBR', 'European Offshore Wind Deployment Centre (Aberdeen)', 'jk', ['UK001'], EN + 'European_Offshore_Wind_Deployment_Centre', sub='sb',
      zh='11 座吸力桶套管', en='11 suction-bucket jackets'),
    F('GBR', 'Galloper', 'mp', ['UK034']),
    F('GBR', 'Greater Gabbard', 'mp', ['UK036']),
    F('GBR', 'Gunfleet Sands 1 & 2', 'mp', ['UK038', 'UK039']),
    F('GBR', 'Gunfleet Sands 3 Demonstration', 'mp', ['UK037']),
    F('GBR', 'Gwynt y Môr', 'mp', ['UK040']),
    F('GBR', 'Hornsea One', 'mp', ['UK043', 'UK044', 'UK045'], 'https://www.offshorewind.biz/2019/04/26/hornsea-one-foundations-all-in-place/',
      zh='174 座全為單樁（2019 年 4 月完工）；OSPAR 把西區列為套管，與建成紀錄不符（DONG 2015 年曾規劃三分之一用吸力桶基礎）',
      en='All 174 are monopiles (completed April 2019); OSPAR lists the western part as jackets, which does not match what was built (in 2015 DONG planned suction buckets for a third of the turbines)'),
    F('GBR', 'Hornsea Two', 'mp', ['UK046', 'UK046A', 'UK046B']),
    F('GBR', 'Humber Gateway', 'mp', ['UK049']),
    F('GBR', 'Kentish Flats', 'mp', ['UK057']),
    F('GBR', 'Kentish Flats Extension', 'mp', ['UK056']),
    F('GBR', 'Levenmouth Demonstration (Methil)', 'jk', ['UK064']),
    F('GBR', 'Lincs', 'mp', ['UK059']),
    F('GBR', 'London Array', 'mp', ['UK060']),
    F('GBR', 'Lynn and Inner Dowsing', 'mp', ['UK061', 'UK052']),
    F('GBR', 'Moray East', 'jk', ['UK141']),
    F('GBR', 'North Hoyle', 'mp', ['UK074']),
    F('GBR', 'Ormonde', 'jk', ['UK076']),
    F('GBR', 'Race Bank', 'mp', ['UK079']),
    F('GBR', 'Rampion', 'mp', ['UK080']),
    F('GBR', 'Rhyl Flats', 'mp', ['UK082']),
    F('GBR', 'Robin Rigg', 'mp', ['UK083', 'UK084']),
    F('GBR', 'Scroby Sands', 'mp', ['UK087']),
    F('GBR', 'Sheringham Shoal', 'mp', ['UK092']),
    F('GBR', 'Teesside (Redcar)', 'mp', ['UK102']),
    F('GBR', 'Thanet', 'mp', ['UK104']),
    F('GBR', 'Triton Knoll', 'mp', ['UK106']),
    F('GBR', 'Walney 1 & 2', 'mp', ['UK107', 'UK108']),
    F('GBR', 'Walney Extension', 'mp', ['UK109', 'UK110']),
    F('GBR', 'West of Duddon Sands', 'mp', ['UK113']),
    F('GBR', 'Westermost Rough', 'mp', ['UK114']),

    # ================================================ 第 2 步（2026-09）：歐洲其他風場（波羅的海、地中海、艾瑟爾湖）與 OSPAR 2024 之後完工的風場
    # ------------------------------------------------ Germany
    F2('DEU', 'Borkum Riffgrund 3', 'mp', ['DE130'], 'https://www.jandenul.com/news/jan-de-nul-kicks-orsteds-borkum-riffgrund-3-offshore-wind-farm-construction',
       zh='83 座單樁', en='83 monopiles'),
    F2('DEU', 'Hohe See', 'mp', ['DE011'], 'https://www.offshorewind.biz/2019/04/11/hohe-see-albatros-foundations-stand-complete/',
       zh='OSPAR 只寫「任一種」、德文維基百科也沒寫；施工新聞：與相鄰的 Albatros 共 87 部風機全用單樁',
       en='OSPAR says “any of these” and German Wikipedia does not say; construction news: all 87 turbines of Hohe See and neighbouring Albatros stand on monopiles'),
    F2('DEU', 'Hooksiel (BARD test turbine)', 'tl', url='https://de.wikipedia.org/wiki/Tripile_(Gr%C3%BCndung)',
       zh='BARD 的三樁試驗機（2016 年拆除）', en='BARD’s tripile pilot turbine (dismantled in 2016)'),
    F2('DEU', 'EnBW Baltic 1', 'mp', url='https://www.enbw.com/company/topics/wind-power/offshore-wind-farm-baltic-1/'),
    F2('DEU', 'EnBW Baltic 2', 'mx', url='https://www.enbw.com/company/topics/wind-power/offshore-wind-farm-baltic-2/', parts=[['mp', 39], ['jk', 41]],
       zh='水深約 35 m 以內用單樁（39 座），更深處用套管（41 座）', en='Monopiles in water up to about 35 m deep (39) and jackets beyond (41)'),
    F2('DEU', 'Wikinger', 'jk', url='https://www.offshorewind.biz/2017/10/26/all-wikinger-turbines-up/', zh='70 座套管', en='70 jackets'),
    F2('DEU', 'Arkona', 'mp', url='https://www.offshorewind.biz/2017/11/09/all-monopiles-installed-at-arkona-offshore-wind-farm-tps-next/',
       zh='60 座單樁', en='60 monopiles'),
    F2('DEU', 'Arcadis Ost 1', 'mp', url='https://parkwind.eu/news/ao1-monopile-installation-completed', zh='XXL 單樁', en='XXL monopiles'),
    F2('DEU', 'Baltic Eagle', 'mp', url='https://www.energyglobal.com/wind/12092023/iberdrola-completes-installation-of-all-50-monopiles-at-baltic-eagle-offshore-wind-farm/',
       zh='50 座單樁', en='50 monopiles'),
    F2('DEU', 'Ems Emden (Enercon E-112 nearshore)', 'cf', url='https://w3.windmesse.de/windenergie/news/1004-erstes-nearshore-projekt-mit-grosswindanlage',
       zh='堤腳外約 40 m 的河口水域中，在鋼板樁圍堰內澆築、由 40 支鋼管樁支撐的混凝土基座；聯邦能源登錄（MaStR）把它列為陸域風機',
       en='In the estuary about 40 m off the dike toe: a concrete base on 40 steel tube piles, cast inside a sheet-pile wall; the federal '
          'energy register (MaStR) lists it as an onshore turbine'),
    F2('DEU', 'Breitling (Rostock)', 'cf', url='https://w3.windmesse.de/windenergie/news/2284-erste-offshore-turbine-in-deutschland-errichtet',
       zh='水深約 2 m 處以鋼板樁圍成、用砂與混凝土築成的基座（直徑 18 m）；聯邦能源登錄（MaStR）把它列為陸域風機',
       en='A sheet-pile ring in about 2 m of water, built up with sand and concrete (18 m across); the federal energy register (MaStR) '
          'lists it as an onshore turbine'),
    # ------------------------------------------------ Netherlands（艾瑟爾湖與 Borssele 試驗場）、Belgium
    F2('NLD', 'Windpark Fryslân', 'mp', url='https://www.offshorewind.biz/2020/11/09/windpark-fryslan-monopiles-halfway-there/',
       zh='89 座單樁（艾瑟爾湖）', en='89 monopiles (IJsselmeer)'),
    F2('NLD', 'Westermeerwind', 'mp', url='https://www.offshore-energy.biz/westermeerwind-foundations-in-place/',
       zh='48 座單樁（艾瑟爾湖）', en='48 monopiles (IJsselmeer)'),
    F2('NLD', 'Windplanblauw offshore wind farm', 'cf',
       url='https://windpowernl.com/2024/08/30/festive-opening-of-dutch-on-and-nearshore-wind-project-windplanblauw/',
       zh='湖中 24 部風機：每座以 22 支鋼管樁（間以板樁）圍成一圈、填砂，上面是直徑約 20 m 的混凝土基座',
       en='The 24 turbines in the lake: each stands on a ring of 22 steel tube piles (with sheet piles between them), filled with sand and '
          'topped by a concrete base about 20 m across'),
    F2('NLD', 'Irene Vorrink (Dronten)', 'mp',
       url='https://windpowernl.com/2022/02/28/vattenfall-starts-decommissioning-of-one-of-the-oldest-operational-dutch-wind-farms/',
       zh='28 座鋼製單樁，立在堤外的水中（2022 年拆除）', en='28 steel monopiles in the water off the dike (dismantled in 2022)'),
    F2('NLD', 'Borssele V (Two Towers innovation site)', 'mp',
       url='https://www.offshore-energy.biz/the-borssele-series-innovation-site-for-the-ever-evolving-industry/',
       zh='2 座單樁；其中一座試用 Slip Joint（單樁與轉接段以錐面套接）', en='2 monopiles; one tests a Slip Joint (a conical connection between the monopile and transition piece)'),
    # ------------------------------------------------ Denmark（波羅的海、大貝爾特、厄勒海峽；北海與卡特加特的在第 1 步）
    F2('DNK', 'Kriegers Flak', 'mp', url='https://group.vattenfall.com/press-and-media/newsroom/2020/all-kriegers-flak-foundations-installed',
       zh='72 座單樁', en='72 monopiles'),
    F2('DNK', 'Rødsand II', 'gb', url='https://m.aarsleff.com/img/6885/0/0/Download/180-r%C3%B8dsand-2-uk',
       zh='混凝土沉箱重力式基礎（與 Nysted 相同）', en='Concrete gravity caissons (as at Nysted)'),
    F2('DNK', 'Nysted (Rødsand I)', 'gb', url='https://m.aarsleff.com/img/7435/0/0/Download/057-r%C3%B8dsand-uk',
       zh='壓艙的混凝土沉箱；2022 年一部風機倒塌拆除、一部停用，其餘 70 部繼續運轉', en='Ballasted concrete caissons; one turbine collapsed and was removed in 2022 and another was taken out of service, leaving 70 in operation'),
    F2('DNK', 'Middelgrunden', 'gb', url='https://ens.dk/media/6684/download', zh='混凝土重力式基礎', en='Concrete gravity bases'),
    F2('DNK', 'Samsø', 'mp', url='https://ens.dk/media/2563/download', zh='10 座單樁，配混凝土轉接段', en='10 monopiles with concrete transition pieces'),
    F2('DNK', 'Sprogø', 'gb', url='https://boskalis.com/about-us/projects/offshore-wind-farm-sprogo', zh='混凝土重力式基礎（每座最重約 1,900 噸）',
       en='Concrete gravity bases (up to about 1,900 t each)'),
    F2('DNK', 'Avedøre Holme', 'gb', url='https://ens.dk/media/2599/download',
       zh='3 座混凝土重力式基座，立在堤外約 2 m 深的水中（依 2008 年環評的設計）', en='3 concrete gravity bases in about 2 m of water off the dike (as designed in the 2008 EIA)'),
    F2('DNK', 'Tunø Knob', 'gb', url='https://www.osti.gov/etdeweb/biblio/630721', zh='箱型沉箱重力式基礎', en='Box-caisson gravity foundations'),
    # ------------------------------------------------ Sweden, Finland
    F2('SWE', 'Lillgrund', 'gb', url='https://www.osti.gov/etdeweb/servlets/purl/979747', zh='鋼筋混凝土重力式基礎，內填壓艙物',
       en='Reinforced-concrete gravity bases filled with ballast'),
    F2('SWE', 'Kårehamn', 'gb', url='https://www.offshorewind.biz/2026/01/23/nordic-renewable-energy-company-acquiring-rwes-swedish-offshore-wind-farm',
       zh='16 座重力式基礎', en='16 gravity-based foundations'),
    F2('SWE', 'Vindpark Vänern (Gässlingegrund)', 'ra', url='https://evwind.aeeolica.org/2010/05/24/the-first-vanern-offshore-wind-farm-inaugurated/5723',
       zh='錨定在湖底岩盤上的基礎（維納恩湖）', en='Anchored to the bedrock of the lake bed (Lake Vänern)'),
    F2('SWE', 'Utgrunden I', 'mp', url='https://www.offshorewind.biz/2018/10/04/swedish-offshore-wind-farm-is-no-more/', zh='7 座單樁（2018 年拆除）',
       en='7 monopiles (dismantled in 2018)'),
    F2('SWE', 'Bockstigen', 'mp', url='https://www.osti.gov/etdeweb/biblio/679603', zh='鑽孔植入石灰岩的單樁', en='Monopiles set in holes drilled into the limestone'),
    F2('FIN', 'Pori Tahkoluoto (Offshore Pori)', 'gb', url='https://hyotytuuli.fi/en/suomen-hyotytuuli-rakentaa-merituulipuiston-porin-tahkoluotoon-2/',
       zh='填石的鋼製重力式基礎（海床是岩盤，無法打單樁；需抵抗海冰）', en='Rock-filled steel gravity bases (the bedrock rules out monopiles; built for ice loads)'),
    F2('BEL', 'Belwind Alstom Haliade demonstrator', 'jk', ['Be003'],
       'https://www.offshorewind.biz/2013/11/20/belgium-alstom-installs-6mw-haliade-offshore-wind-turbine',
       zh='61 m 高的套管，架在預先打入海床的樁上（2013 年）；OSPAR 把它併在 Belwind 一期（單樁）裡',
       en='A 61 m jacket set on pre-driven piles (2013); OSPAR merges it into Belwind phase 1 (monopiles)'),
    # ------------------------------------------------ United Kingdom
    F2('GBR', 'Seagreen Phase 1', 'jk', ['UK089'], 'https://www.sserenewables.com/news-and-views/2023/04/final-jacket-foundation-installed-on-seagreen/', sub='sb',
       zh='114 座吸力桶套管；OSPAR 這筆沒有寫型式', en='114 suction-bucket jackets; OSPAR’s record gives no type'),
    F2('GBR', 'Moray West', 'mp', ['UK142'], 'https://www.moraywest.com/news/moray-west-celebrates-final-monopile-installation',
       zh='全部為單樁（2024 年 4 月裝完）；OSPAR 列為套管，與建成紀錄不符', en='All monopiles (completed April 2024); OSPAR lists jackets, which does not match what was built'),
    F2('GBR', 'Neart na Gaoithe', 'jk', ['UK068'], 'https://www.saipem.com/en/media/press-releases/2023-10-24/saipem-successfully-completed-installation-works-scotland-neart-na',
       zh='54 座套管', en='54 jackets'),
    F2('GBR', 'Dogger Bank A', 'mp', ['UK014'], 'https://doggerbank.com/construction/foundation-installation-campaign-begins-on-dogger-bank-b/',
       zh='95 座單樁（附轉接段）', en='95 monopiles with transition pieces'),
    F2('GBR', 'Sofia', 'mp', ['UK138'], 'https://www.rwe.com/en/press/rwe-offshore-wind-gmbh/2025-07-15-sofia-offshore-wind-farm-completes-installation-of-foundations/',
       zh='100 座加長單樁（不另加轉接段）', en='100 extended monopiles (no separate transition piece)'),
    # ------------------------------------------------ France, Ireland, Italy, Spain
    F2('FRA', "Îles d'Yeu et de Noirmoutier", 'mp', ['FR06'], 'https://www.deme-group.com/news/all-foundations-installed-iles-dyeu-and-noirmoutier-offshore-wind-farm',
       zh='61 座鑽孔植入的單樁', en='61 drilled monopiles'),
    F2('FRA', 'Calvados (Courseulles-sur-Mer)', 'mp', ['FR01'],
       'https://www.meretmarine.com/fr/energies-marines/parc-eolien-du-calvados-le-seaway-strashnov-est-arrive-au-havre-pour-installer-des-monopieux',
       zh='64 座單樁（興建中）', en='64 monopiles (under construction)'),
    F2('IRL', 'Arklow Bank Phase 1', 'mp', ['IE01'], 'https://www.ge.com/news/press-releases/arklow-bank-wind-park-irish-sea-nearing-completion',
       zh='7 座打入式單樁', en='7 driven monopiles'),
    F2('ITA', 'Beleolico (Taranto)', 'mp', url='https://www.offshorewind.biz/2022/01/13/foundations-stand-at-first-mediterranean-offshore-wind-farm/',
       zh='10 座單樁；地中海第一座離岸風場', en='10 monopiles; the first offshore wind farm in the Mediterranean'),
    F2('ESP', 'Elican / Elisa (Gran Canaria)', 'gb', url='https://cordis.europa.eu/project/id/691919',
       zh='重力式基礎配伸縮式塔架，可自行安裝的原型機', en='A gravity-based foundation with a telescopic tower; a self-installing prototype'),

    # ================================================ 第 3 步（2026-09）：浮動式風場的細分型式
    # ------------------------------------------------ Europe
    F3('GBR', 'Hywind Scotland', 'fl', url='https://www.equinor.com/energy/hywind-scotland', sub='spar',
       zh='Equinor 的單柱式浮台', en='Equinor’s spar floaters'),
    F3('GBR', 'Kincardine', 'fl', url='https://www.principlepower.com/projects/kincardine-offshore-wind-farm', sub='semi',
       zh='Principle Power 的 WindFloat 半潛式平台', en='Principle Power’s WindFloat semi-submersibles'),
    F3('PRT', 'WindFloat Atlantic', 'fl', url='https://www.principlepower.com/projects/windfloat-atlantic', sub='semi',
       zh='Principle Power 的 WindFloat 半潛式平台', en='Principle Power’s WindFloat semi-submersibles'),
    F3('PRT', 'WindFloat 1 (Aguçadoura demo)', 'fl', url='https://www.principlepower.com/projects/windfloat1', sub='semi',
       zh='第一部裝在半潛式平台上的浮動式風機（2011–2016 年；之後移到蘇格蘭 Kincardine 再運轉到 2020 年）',
       en='The first floating turbine on a semi-submersible (2011–2016; later moved to Kincardine in Scotland, where it ran until 2020)'),
    F3('FRA', 'Floatgen (SEM-REV)', 'fl', url='https://www.bw-ideol.com/en/floatgen-demonstrator', sub='barge',
       zh='BW Ideol 的阻尼池式駁船', en='BW Ideol’s Damping Pool barge'),
    F3('FRA', 'EolMed (Gruissan)', 'fl', url='https://www.bw-ideol.com/en/eolmed-project', sub='barge',
       zh='BW Ideol 的阻尼池式駁船（鋼造）', en='BW Ideol’s Damping Pool barges (steel)'),
    F3('FRA', 'Les Éoliennes Flottantes du Golfe du Lion (EFGL)', 'fl', url='https://www.principlepower.com/projects/efgl', sub='semi',
       zh='Principle Power 的 WindFloat 半潛式平台', en='Principle Power’s WindFloat semi-submersibles'),
    F3('ESP', 'DemoSATH (BiMEP)', 'fl', url='https://saitec-offshore.com/en/sath/', sub='barge',
       zh='Saitec 的 SATH 混凝土駁船', en='Saitec’s SATH concrete barge'),
    # ------------------------------------------------ Asia
    F3('CHN', 'Mingyang OceanX (Tiancheng) floating', 'fl', url='https://www.mlit.go.jp/kowan/content/001869831.pdf', sub='semi',
       zh='一座浮台上兩部 8.3 MW 風機，浮台由浮筒與混凝土構件組成（日本國土交通省的調查列為半潛式）',
       en='Two 8.3 MW turbines on one floater of buoys and concrete members (listed as a semi-submersible in a survey by Japan’s MLIT)'),
    F3('CHN', 'Haiyou Guanlan (CNOOC floating)', 'fl', url='https://www.offshorewind.biz/2023/05/22/china-connects-deepwater-floating-wind-platform-to-wenchang-oil-field/',
       sub='semi', zh='半潛式；供電給文昌油田群，不接公用電網', en='Semi-submersible; it supplies the Wenchang oilfield grid, not the public grid'),
    F3('CHN', 'Haiyou Anlan (CNOOC floating)', 'fl', url='https://www.news.cn/tech/20260806/18f047cf51d840c489e283b9d1669742/c.html', sub='tlp',
       zh='張力腿式平台（新華社：「首座16兆瓦張力腿深遠海浮式風電平台」）；供電給陸豐油田，不接公用電網',
       en='Tension-leg platform (Xinhua: “the first 16 MW tension-leg deep-sea floating wind platform”); it supplies the Lufeng oilfield, not the public grid'),
    F3('CHN', "Yangjiang Shapa 'Sanxia Yinling' floating", 'fl',
       url='http://www.sasac.gov.cn/n4470048/n22624391/n26705666/n26705673/n26705740/c26786615/content.html', sub='semi',
       zh='半潛式平台', en='Semi-submersible platform'),
    F3('JPN', 'Hibiki floating demo (NEDO)', 'fl', url='https://www.nedo.go.jp/news/press/AA5_101117.html', sub='barge',
       zh='鋼製駁船式浮台，搭載兩葉片 3 MW 風機', en='A steel barge floater carrying a two-bladed 3 MW turbine'),
    F3('JPN', 'Goto Sakiyama floating demonstration', 'fl', url='https://www.toda.co.jp/business/ecology/haenkaze/about/facility.html', sub='spar',
       zh='戶田建設的混合式單柱浮台「はえんかぜ」', en='Toda’s hybrid spar “Haenkaze”'),
    F3('JPN', 'Goto City Offshore floating project', 'fl', url='https://www.toda.co.jp/news/2026/20260105_006181.html', sub='spar',
       zh='8 座混合式單柱浮台（上段鋼、下段混凝土）', en='8 hybrid spars (steel upper part, concrete lower part)'),
    F3('JPN', 'Fukushima FORWARD floating demo', 'fl', url='https://www.fukushima-forward.jp/reference/pdf/study086.pdf',
       zh='兩部半潛式（2 MW、7 MW V 型）與一部單柱式（5 MW），型式不同，所以不標單一細分型式',
       en='Two semi-submersibles (2 MW and a V-shaped 7 MW) and one spar (5 MW); the types differ, so no single sub-type is given'),

    # ================================================ 第 5 步（2026-09 起）：中國、越南
    # 依使用者 2026-09-27 的「亞洲逐案覆核」。2026-09-30 以 check_quotes 核對：上海市政府、福建省工信廳、澎湃、新浪財經（補貼公示）、
    # 中廣核的頁面 OK；三峽集團自家網域（eps／tgdc／www.ctg.com.cn、ctgne.com）在核對環境連不上，如東 H6、H10 兩列仍以三峽網頁為出處（見 TODO）
    F5('CHN', 'Donghai Bridge', 'pc', url='https://www.shanghai.gov.cn/nw5827/20200905/0001-5827_437507.html',
       zh='34 部 3 MW 風機立在高樁混凝土承台上（上海市政府：2010 年 6 月 8 日全部風機併網），中國第一座大型離岸風場',
       en='34 × 3 MW turbines on high-rise pile caps with concrete caps (Shanghai government: all turbines connected on 8 June 2010); China’s first large offshore wind farm'),
    F5('CHN', 'CTG Rudong H6', 'mp', url='https://eps.ctg.com.cn/cms/channel/1ywgg1/17129.htm',
       zh='100 部 4 MW 風機，全部為單樁（2021 年 12 月全容量併網；與 H10 共用柔性直流送出）',
       en='100 × 4 MW turbines, all on monopiles (fully connected in December 2021; shares a flexible HVDC link with H10)'),
    F5('CHN', 'CTG Rudong H10', 'mx', url='https://eps.ctg.com.cn/cms/channel/1ywgg1/19830.htm', parts=[['mp', 77], ['bk', 23]],
       zh='100 部 4 MW 風機：77 座單樁、23 座複合筒（2021 年 12 月全容量併網）',
       en='100 × 4 MW turbines: 77 on monopiles and 23 on composite buckets (fully connected in December 2021)'),
    F5('CHN', "CTG Zhangpu Liu'ao Phase 2", 'jk', url='https://gxt.fj.gov.cn/zwgk/xw/hydt/snhydt/202405/t20240523_6453562.htm',
       zh='四樁套管（福建省工信廳：機位水深逾 46 m，設計團隊採「4 樁導管架」）；28 部 13 MW 以上機組（含 6 部 16 MW），2024 年 6 月全容量併網（澎湃新聞）',
       en='Four-pile jackets (Fujian industry department: over 46 m of water, the design team chose a four-pile jacket); 28 turbines of 13 MW and above (six of 16 MW), fully connected in June 2024 (The Paper)'),
    # 中廣核的基礎監測合同列出 49 座單樁與 16 座全鋼筒型，與使用者的逐案覆核相同
    F5('CHN', "Datang Nan'ao Lemen I", 'mp', url='https://www.shantou.gov.cn/attachment/0/156/156038/2544766.pdf',
       zh='35 部上海電氣 7 MW 全部為無過渡段單樁：變更海域使用補充論證報告書（汕頭市政府公開，依「實際建設方案」論證；2021-03-16 海上開工、2021-12-29 全容量併網）'
          '寫「均採用無過渡段單樁基礎方案」，並引竣工環境保護驗收調查報告：「本工程海上風機採用單樁基礎」。',
       en='All 35 Shanghai Electric 7 MW turbines stand on monopiles without transition pieces: the supplementary sea-use change report (Shantou government, argued on the '
          'as-built scheme; offshore works from 16 Mar 2021, full grid connection 29 Dec 2021) says all use transition-piece-free monopiles and cites the completion '
          'environmental acceptance report: "the offshore turbines of this project use monopile foundations".'),
    F5('CHN', 'Longyuan Rudong Intertidal 150 MW Demo', 'mx', url='https://niigata.china-consulate.gov.cn/zgxw/201112/t20111230_9292410.htm',
       parts=[['mp', 37], ['jk', 21]],
       zh='58 部：21 部西門子 2.38 MW 為多樁導管架，其餘 37 部（一期 17 部華銳 3 MW、二期 20 部金風 2.5 MW）為直徑 5.2 m 單樁。一期竣工時「17 台單樁、21 台多樁導管架」'
          '（中國駐新潟總領事館轉載，2011-12-30）；二期金風機組為單樁出自 Power Technology 與 Energy Monitor（同一出版集團）；南通海洋水建也寫全場只用單樁與多樁導管架兩種。',
       en='58 turbines: the 21 Siemens 2.38 MW units on multi-pile jackets and the other 37 (17 Sinovel 3 MW in phase I, 20 Goldwind 2.5 MW in phase II) on 5.2 m monopiles. '
          'Phase I’s 17 monopiles + 21 multi-pile jackets at completion (Chinese Consulate in Niigata repost, 30 Dec 2011); the phase-II Goldwind monopiles from Power Technology '
          'and Energy Monitor (same publisher); Nantong Ocean Hydraulic also says the farm used only monopiles and multi-pile jackets.'),
    F5('CHN', 'CGN Rudong H8', 'mx', url='https://ecp.cgnpc.com.cn/view/staticpags/zgh_zbgg/8a488fc36fae46600171bacf23d163d0.html',
       parts=[['mp', 49], ['bk', 16]],
       zh='65 部風機：49 座單樁、16 座全鋼筒型（與複合筒同為以負壓沉入的單筒基礎，筒體與過渡段全為鋼製）；2021 年 12 月全容量併網',
       en='65 turbines: 49 on monopiles and 16 on all-steel buckets (single buckets sunk by suction, like the composite bucket, '
          'but with a steel transition piece); fully connected in December 2021'),
    # 2026-09-30 第二批（出處原文皆以 check_quotes 核對）· second batch, every quote checked
    F5('CHN', 'CTG Dafeng H8-1 (800 MW)', 'mp', url='https://www.js.chinanews.com.cn/news/2025/0916/230110.html',
       zh='98 部風機全部為單樁（樁徑 7–9 m、最長 97 m、最重 1,713 t，中新網 2025 年 9 月）；2025 年 12 月 15 日全容量併網',
       en='All 98 turbines on monopiles (7–9 m in diameter, up to 97 m long and 1,713 t; China News Service, September 2025); fully connected on 15 December 2025'),
    F5('CHN', 'Guangxi Fangchenggang A', 'jk', url='http://www.sasac.gov.cn/n2588025/n2588129/c32426404/content.html',
       zh='83 部 8.5 MW 全部為三樁嵌岩套管：岩基海床，鋼管樁鑽孔嵌岩後灌漿，套管三腳插入樁內（國資委、新華網）；中國第一座全場採嵌岩基礎的離岸風場',
       en='All 83 × 8.5 MW turbines on three-pile rock-socketed jackets: rock seabed, the steel piles are drilled into the rock and grouted and the three jacket legs set into them (SASAC, Xinhua); China’s first offshore farm with rock-socketed foundations throughout'),
    F5('CHN', 'CR Power Lianjiang Waihai', 'mx', url='http://www.chinapower.com.cn/flfd/xmjz/20240429/244321.html', parts=[['mp', 7], ['jk', 32]],
       zh='39 部 18 MW 機組：7 座單樁（直徑 10 m）、32 座套管（中國電力網 2024 年 4 月的塔筒供貨報導）',
       en='39 × 18 MW turbines: 7 on monopiles (10 m in diameter) and 32 on jackets (China Power, April 2024, on the tower supply)'),
    F5('CHN', 'Shenergy Hainan CZ2 (Danzhou)', 'mp', url='https://finance.sina.com.cn/jjxw/2024-05-26/doc-inawpazx5145233.shtml',
       zh='67 部 9 MW 風機各立在一根單樁上（海南日報 2024 年 5 月的施工報導，單樁長 95.7 m、直徑 8.8 m、重 1,639 t）',
       en='67 × 9 MW turbines, each on a monopile (Hainan Daily construction report, May 2024: 95.7 m long, 8.8 m in diameter, 1,639 t)'),
    F5('CHN', 'CGN Shanwei Houhu', 'mx', url='https://www.chinanews.com/m/cj/2021/11-25/9616090.shtml', parts=[['mp', 82], ['jk', 9]],
       zh='91 部 5.5 MW：82 座單樁、8 座四樁套管、1 座吸力筒套管（中新網 2021 年 11 月全數併網報導）',
       en='91 × 5.5 MW: 82 monopiles, 8 four-pile jackets and 1 suction-bucket jacket (China News Service, November 2021, on full grid connection)'),
    F5('CHN', 'Guangdong Energy Yangjiang Qingzhou 1&2', 'jk', url='https://www.ccedia.com/gas_detail/c-_detailId=1632992535936905216.html',
       zh='92 部 11 MW 全部為套管（水深 35–43 m；施工標段為 92 座套管與基礎鋼管樁，中國能源新聞網另提「新型過渡段結構的深水區導管架基礎」）；2023 年 12 月 12 日全容量併網',
       en='All 92 × 11 MW turbines on jackets (35–43 m of water; the construction lot covers 92 jackets and their pin piles, and China Energy News notes a deep-water jacket with a new transition piece); fully connected on 12 December 2023'),
    # 2026-09-30 第三批（出處原文皆以 check_quotes 核對）· third batch, every quote checked
    F5('CHN', 'SPIC Binhai North H2', 'mp', url='http://www.jsea.org.cn/end.asp?id=1674',
       zh='100 部 4 MW 全部為大直徑無過渡段單樁（2017 年 5 月至 2018 年 3 月沉樁；江蘇省電機工程學會的華電重工工法介紹）',
       en='All 100 × 4 MW turbines on large-diameter monopiles without a transition piece (piled May 2017 to March 2018; Jiangsu Society for Electrical Engineering, on Huadian Heavy Industry’s method)'),
    F5('CHN', 'Shandong Bozhong B2', 'mp', url='http://www.cpem.org.cn/list68/44814.html',
       zh='59 部 8.5 MW 全部為單樁（2022 年 10 月首樁直徑 7.2 m、長 82 m、重 967 t；CPEM 轉載國家能源集團報導，國家能源集團 2023 年 6 月全容量併網報導寫 59 部）',
       en='All 59 × 8.5 MW turbines on monopiles (first pile October 2022: 7.2 m in diameter, 82 m long, 967 t; CPEM reprint of the China Energy report, whose June 2023 full-connection release gives 59 turbines)'),
    F5('CHN', 'Huarun Cangnan 1 / CR Power', 'mp', url='https://www.cpem.org.cn/list68/64746.html',
       zh='49 部（6.25 與 10 MW）全部為單樁：原設計 29 座單樁＋48 座高樁承台，改為全場單樁（華潤電力建設紀實，CPEM 轉載）；2022 年 12 月 28 日全容量併網',
       en='All 49 turbines (6.25 and 10 MW) on monopiles: the design of 29 monopiles plus 48 high-rise pile caps was changed to monopiles throughout (CR Power construction account, CPEM reprint); fully connected on 28 December 2022'),
    F5('CHN', 'Jiangsu Qidong H1+H2', 'mp', url='https://www.ne21.com/news/show-163136.html',
       zh='H1、H2 共 84 部風機各一根單樁（中交一航局承建 84 根，2021 年 6 月打到第 64 根；南通發布）',
       en='84 turbines across H1 and H2, one monopile each (84 piles by CCCC First Harbor, the 64th driven in June 2021; Nantong government release)'),
    F5('CHN', 'CGN Fanshi I', 'jk', url='https://www.yjrb.com.cn/content/c211953.html',
       zh='73 部（22 部 13.6 MW＋51 部 14 MW）用四樁套管，水深 40–48 m（陽江日報的施工報導，32 號機位四根套管樁）',
       en='73 turbines (22 × 13.6 MW and 51 × 14 MW) on four-pile jackets in 40–48 m of water (Yangjiang Daily construction report on the four jacket piles at position 32)'),
    # 2026-10-01 第四批（出處原文皆以 check_quotes 核對）· fourth batch, every quote checked
    F5('CHN', 'Shandong Huaneng Offshore L Area wind farm', 'jk', url='http://wap.sasac.gov.cn/n2588025/n2588124/c35402269/content.html',
       zh='42 部 12 MW 全部用四樁套管（最高 83.9 m），水深 52–56 m、離岸約 70 km，中國水深最深的商轉離岸風場；2026 年 4 月 7 日全容量併網（國資委、人民日報）',
       en='All 42 × 12 MW turbines on four-pile jackets (up to 83.9 m tall) in 52–56 m of water about 70 km offshore, China’s deepest operating offshore farm; fully connected on 7 April 2026 (SASAC, People’s Daily)'),
    F5('CHN', 'SPIC Peninsula South U1', 'mp', url='https://www.163.com/dy/article/K7QMU0850514R9KE.html',
       zh='106 部 8.5 MW 全部為單樁：一期 450 MW（53 部，2023 年 11 月併網）獲 2025 年度中國電力優質工程，得獎說明寫「風機基礎單樁最大樁重 1450 噸」（網易轉載）；'
          '二期 53 部由龍源振華 2024 年 9 月全部沉樁完成（世紀新能源網；原本另列為「Shandong Haiwei Peninsula South U」的重複紀錄已於 2026-10 刪除）。',
       en='All 106 × 8.5 MW on monopiles: phase 1 (450 MW, 53 units, connected Nov 2023) won a 2025 China Electric Power Quality Project award whose citation gives '
          '"turbine foundation monopiles up to 1,450 t" (via 163.com); all 53 monopiles of phase 2 were driven by Longyuan Zhenhua in Sept 2024 (ne21; the duplicate record '
          '"Shandong Haiwei Peninsula South U" for phase 2 was removed in Oct 2026).'),
    F5('CHN', 'Zhejiang Cangnan 2 Offshore wind farm', 'mp', url='https://news.qq.com/rain/a/20230419A0355R00',
       zh='華能蒼南 2 號 36 部 8.5 MW 全部為單樁（新京報 2023 年 4 月「國內在建最大單樁風電項目」報導；最長樁 118 m、2,328 t，CPEM）',
       en='Huaneng’s Cangnan 2: all 36 × 8.5 MW turbines on monopiles (Beijing News, April 2023, “China’s largest monopile wind project under construction”; longest pile 118 m and 2,328 t, CPEM)'),
    F5('CHN', 'Huaneng Lingao CZ1', 'mp', url='http://mm.chinapower.com.cn/flfd/xmjz/20241118/267592.html',
       zh='60 部 10 MW 全部為單樁（直徑 8.25–9.6 m、長 82–109 m、重 1,191–1,938 t；2024 年 11 月 17 日全部沉樁完成，中國電力網）',
       en='All 60 × 10 MW turbines on monopiles (8.25–9.6 m in diameter, 82–109 m long, 1,191–1,938 t; all driven by 17 November 2024, China Power)'),
    F5('CHN', 'Zhejiang Xiangshan 1 Offshore wind farm', 'mx', url='https://www.ceic.com/gjnyjtww/chnyxfc/202101/e0582b74a0ef45c88a70e33ecc70a6ff.shtml', parts=[['pc', 43], ['mp', 54]],
       zh='一期 41 部 6.2 MW：23 座高樁承台＋18 座單樁（國家能源集團）；二期 56 部 9 MW：36 座單樁＋160 根群樁（象山發布經中國線纜網），即 20 座高樁承台；兩期合計 43 座承台、54 座單樁',
       en='Phase 1, 41 × 6.2 MW: 23 high-rise pile caps and 18 monopiles (China Energy); phase 2, 56 × 9 MW: 36 monopiles plus 160 group piles (Xiangshan government via China Cable), i.e. 20 pile caps; 43 caps and 54 monopiles in all'),
    # ================================================ 第 4 步（2026-09）：台灣、日本、韓國、美國
    # ------------------------------------------------ Taiwan
    F4('TWN', 'Formosa 1 Phase 1', 'mp',
       url='https://www.siemensgamesa.com/global/en/home/press-releases/siemens-gamesa-awarded-120-mw-expansion-of-taiwans-pioneering-formosa-1-offshore-wind-power-plant.html',
       zh='2 座單樁，2016 年與兩部示範機組一起安裝', en='2 monopiles, installed in 2016 together with the two demonstration turbines'),
    F4('TWN', 'Formosa 1 Phase 2', 'mp', url='https://www.jandenul.com/news/all-foundations-formosa-1-phase-2-installed',
       zh='20 座單樁，配灌漿接合的轉接段', en='20 monopiles with grouted transition pieces'),
    F4('TWN', 'Taipower Offshore Phase 1 (Changhua)', 'jk', url='https://www.jandenul.com/our-projects/offshore-windfarm-changhua-taiwan',
       zh='21 座四腳套管配轉接段，各以 4 支預打的基樁灌漿固定（共 84 支）',
       en='21 four-legged jackets with transition pieces, each grouted onto four pre-installed pin piles (84 in total)'),
    F4('TWN', 'Formosa 2', 'jk', url='https://www.jandenul.com/news/jan-de-nul-completes-foundation-and-cable-installation-formosa-2-offshore-wind-farm',
       zh='47 座套管，共 188 支基樁（2022 年裝完）', en='47 jackets on 188 pin piles (installed in 2022)'),
    F4('TWN', 'Greater Changhua 1 & 2a', 'jk', url='https://cdn.orsted.com/-/media/www/docs/corp/tw/en-chw-1-and-2a-case-study.pdf',
       zh='111 座套管，每座 3 支基樁（共 333 支）；其中 6 座全部在台灣製造',
       en='111 jackets, each on three pin piles (333 in total); six of them were built entirely in Taiwan'),
    F4('TWN', 'Changfang & Xidao', 'jk', url='https://www.offshorewind.biz/2023/07/17/all-foundations-stand-at-changfang-xidao-wind-farms-offshore-taiwan/',
       zh='62 座三腳套管（世紀風電製造），共 186 支基樁', en='62 three-legged jackets (built by Century Wind Power) on 186 pin piles'),
    F4('TWN', 'Zhong Neng', 'jk', url='https://www.offshorewind.biz/2024/03/04/all-foundations-in-at-zhong-neng-wind-farm-offshore-taiwan/',
       zh='31 座套管（世鎧精密製造），共 93 支國產基樁', en='31 jackets (built by Sing Da Marine Structure) on 93 locally made pin piles'),
    F4('TWN', 'Yunlin', 'mp', url='https://www.yunlin-offshore.com/en/technology',
       zh='80 座直徑 8 m 的單樁配轉接段（另有 3 座 2021–2023 年發生溜樁的單樁已移除，不計在內）',
       en='80 monopiles 8 m across with transition pieces (three earlier ones that suffered pile runs in 2021–2023 were removed and are not counted)'),
    F4('TWN', 'Hai Long 2 & 3', 'jk', url='https://www.cdwe.com.tw/news_detail.php?id=151',
       zh='73 座套管，每座 3 支預打基樁（共 219 支），2025 年 8 月裝完',
       en='73 jackets, each on three pre-installed pin piles (219 in total), completed in August 2025'),
    F4('TWN', 'Greater Changhua 2b & 4', 'jk',
       url='https://heerema.com/news/heerema-sets-down-last-suction-bucket-jacket-at-%C3%B8rsteds-greater-changhua-2a-4', sub='sb',
       zh='66 座全數為吸力桶套管（不打樁）：大彰化西南第二階段 24 座、西北 42 座，是亞太第一座全用吸力桶的風場',
       en='All 66 are suction-bucket jackets (no piling): 24 at Greater Changhua 2b and 42 at Greater Changhua 4, the first such farm in the Asia-Pacific'),
    F4('TWN', 'Taipower Offshore Phase 2', 'jk', url='https://tpc-offshorewind-p2.tw/foundation',
       zh='31 座四腳套管配轉接段，以 124 支預打基樁灌漿固定', en='31 four-legged jackets with transition pieces, grouted onto 124 pre-installed pin piles'),
    # ------------------------------------------------ Japan（港灣內的風場以 NEDO 的支持構造分類為準）
    F4('JPN', 'Setana semi-offshore', 'pc', url='https://www.nedo.go.jp/content/100889997.pdf',
       zh='NEDO 稱「ドルフィン」，即高樁承台：4 支直樁（長 27 m、直徑 1.1 m）上加寬約 10 m、厚 2 m 的混凝土承台',
       en='NEDO calls it a “dolphin”, that is a high-rise pile cap: four vertical piles (27 m long, 1.1 m across) under a concrete cap about 10 m wide and 2 m thick'),
    F4('JPN', 'Sakata Port semi-offshore', 'pc', url='https://www.nedo.go.jp/content/100890000.pdf',
       zh='NEDO 稱「ドルフィン」，即高樁承台：8 支直樁（長 27 m、直徑 1 m）上加直徑 12 m、厚 2.5 m 的八角形混凝土承台；2023 年撤除',
       en='NEDO calls it a “dolphin”, that is a high-rise pile cap: eight vertical piles (27 m long, 1 m across) under an octagonal concrete cap 12 m across and 2.5 m thick; removed in 2023'),
    F4('JPN', 'Kamisu Phase 1 (Wind Power Ibaraki)', 'mp', url='https://jcmanet.or.jp/bunken/kikanshi/2011/12/014.pdf',
       zh='7 座直徑 3.5 m、長 24.5 m 的單樁，配灌漿接合的套管接頭，自岸上以履帶式吊車打設',
       en='7 monopiles 3.5 m across and 24.5 m long with grouted joint sleeves, driven from the shore with a crawler crane'),
    F4('JPN', 'Kamisu Phase 2', 'mp',
       url='https://www.jepoc.or.jp/magazine/magazine.php?_w=magazine&_x=kikan_detail&kikan_m_id=17&kikan_n_id=444',
       zh='8 座單樁；因鄰近 275 kV 輸電線，改以自升式平台船打樁', en='8 monopiles; driven from a jack-up vessel because of the 275 kV lines nearby'),
    F4('JPN', 'Choshi Offshore Demonstration (NEDO/TEPCO)', 'gb', url='https://www.kajima.co.jp/news/press/201302/27c1-j.htm',
       zh='預力混凝土沉箱重力式基礎（2,400 噸），半潛拖運到場後灌入銅爐碴壓艙，合計約 5,400 噸',
       en='A prestressed-concrete caisson gravity base (2,400 t), towed out half-submerged and then filled with copper-slag ballast, 5,400 t in all'),
    F4('JPN', 'Kitakyushu Offshore Demonstration (NEDO/J-Power)', 'gb', url='https://www.nedo.go.jp/content/100890005.pdf',
       zh='J-POWER 的「ハイブリッド重力式」：拋石基床上放預鑄混凝土底版，上面架內填混凝土的鋼製套管；2019 年 9 月撤除風機與上部結構，底版留作研究設施',
       en='J-Power’s “hybrid gravity” foundation: a precast concrete base slab on a rubble mound carrying a steel jacket filled with concrete; the turbine and substructure were removed in September 2019 and the base was kept as a research facility'),
    F4('JPN', 'Noshiro Port', 'mp', url='https://www.kajima.co.jp/news/press/202003/26c1-j.htm',
       zh='20 座單樁配轉接段（鹿島與住友電工統包）', en='20 monopiles with transition pieces (Kajima and Sumitomo Electric EPCI)'),
    F4('JPN', 'Akita Port', 'mp', url='https://www.kajima.co.jp/news/press/202003/26c1-j.htm',
       zh='13 座單樁配轉接段（鹿島與住友電工統包）', en='13 monopiles with transition pieces (Kajima and Sumitomo Electric EPCI)'),
    F4('JPN', 'Nyuzen Offshore Wind Farm', 'mp', url='https://www.shimz.co.jp/works/jp_ene_202308_nyuzen.html',
       zh='3 座直徑 5.5 m、長 48.1–51.6 m 的單樁，不加轉接段（日本首例），清水建設設計施工',
       en='3 monopiles 5.5 m across and 48.1–51.6 m long with no transition piece (a first in Japan), designed and built by Shimizu'),
    F4('JPN', 'Ishikari Bay New Port', 'jk', url='https://www.eng.nipponsteel.com/news/detail/20220909/',
       zh='14 座四腳套管，固定在預打的鋼管樁上（海床軟弱，是日本第一座套管式離岸風場）',
       en='14 four-legged jackets fixed to pre-driven steel pipe piles (chosen for the soft seabed; Japan’s first jacket-founded offshore farm)'),
    F4('JPN', 'Kitakyushu Hibikinada', 'jk', url='https://hibikiwindenergy.co.jp/news/2026/0601.html',
       zh='25 座套管，分 4 樁與 8 樁兩型、共 144 支樁，依海床分別用全套管、RS-plus 與打擊三種工法（水深 8–30 m）',
       en='25 jackets in two variants (4-pile and 8-pile), 144 piles in all, installed by three methods (all-casing, RS-plus and driving) to suit the seabed, in 8–30 m of water'),
    # ------------------------------------------------ South Korea
    F4('KOR', 'Jeju Woljeong test (Doosan)', 'jk',
       url='https://cloudcdn.taiwantradeshows.com.tw/2019/energytaiwan/download/Wind-Energy-Forum-KR.pdf',
       zh='2 部試驗機各立在鋼製套管上：能源技術研究院說明 2 MW 那座是以短基樁固定的傾斜兩段式套管；斗山 3 MW 那座只有 2019 年的產業簡報寫明型式',
       en='Both test turbines stand on steel jackets: KIER describes the 2 MW unit’s inclined two-stage jacket held by short pin piles, while for Doosan’s 3 MW unit only a 2019 industry presentation states the type'),
    F4('KOR', 'Tamra (Jeju Hangyeong)', 'jk', url='http://tamra-owp.co.kr/2019/sub0206.php',
       zh='10 座套管，基樁以反循環（RCD）鑽入玄武岩海床後灌漿固定',
       en='10 jackets whose pin piles were drilled into the basalt seabed with reverse-circulation drilling (RCD) and grouted'),
    F4('KOR', 'Southwest Offshore Demonstration (Seonam)', 'jk', url='http://www.e2news.com/news/articleView.html?idxno=101605',
       zh='20 座套管：19 座打樁式（含 2 號機浦項的研發用套管），7 號機是韓電電力研究院的吸力桶套管',
       en='20 jackets: 19 piled (including POSCO’s R&D jacket under turbine 2) and one suction-bucket jacket by KEPCO’s research institute under turbine 7'),
    F4('KOR', 'Jeju Hanlim', 'jk', url='https://www.kgs-m.org/magazine/kgsm/sm-35/pt-post/nd-582',
       zh='18 座套管，採後打樁：先整平玄武岩放置套管，再以反循環（RCD）鑽孔打樁灌漿',
       en='18 jackets, post-piled: set on pre-drilled, levelled basalt and then fixed with RCD-drilled, grouted pin piles'),
    F4('KOR', 'Yeonggwang Nakwol', 'mp', url='https://www.electimes.com/news/articleView.html?idxno=368993',
       zh='64 座單樁（GS Entec 製，長 60.2–71.2 m、底部直徑 7.5 m）；韓國第一座改用單樁的大型離岸風場',
       en='64 monopiles (made by GS Entec, 60.2–71.2 m long and 7.5 m across at the base); the first large Korean farm to choose monopiles instead of jackets'),
    F4('KOR', 'Jeonnam Offshore Wind 1', 'mp', url='https://www.epj.co.kr/news/articleView.html?idxno=37579',
       zh='10 座單樁，韓國第一座以單樁為基礎的離岸風場', en='10 monopiles; the first monopile-founded offshore wind farm in Korea'),
    # ------------------------------------------------ United States
    F4('USA', 'Block Island', 'jk',
       url='https://www.windpowerengineering.com/historic-milestone-for-u-s-offshore-wind-block-island-wind-farm-installs-steel-in-the-water/',
       zh='5 座四腳套管（各約 400 噸），以穿過套管腳打入的基樁固定；美國第一座離岸風場',
       en='5 four-legged jackets (about 400 t each) fixed by pin piles driven through the legs; the first offshore wind farm in the USA'),
    F4('USA', 'Coastal Virginia Offshore Wind (CVOW) Pilot', 'mp',
       url='https://eew-group.com/projects-references/success-stories/news-detail/coastal-virginia-offshore-wind-project/',
       zh='2 座單樁（877 噸、直徑 7.8 m）配轉接段', en='2 monopiles (877 t, 7.8 m across) with transition pieces'),
    F4('USA', 'South Fork Wind', 'mp', url='https://www.offshorewind.biz/2023/08/10/all-monopiles-up-for-new-yorks-first-offshore-wind-farm/',
       zh='12 座風機單樁，2023 年 6–8 月安裝（海上變電站另立在第 13 座單樁上）',
       en='12 turbine monopiles installed between June and August 2023 (a 13th carries the offshore substation)'),
    F4('USA', 'Vineyard Wind 1', 'mp', url='https://www.deme-group.com/news/offshore-works-kick-vineyard-wind-farm-us-installation-first-foundation',
       zh='62 座風機單樁配轉接段，2023 年 6 月起安裝（海上變電站另有單樁）',
       en='62 turbine monopiles with transition pieces, installed from June 2023 (the offshore substation stands on its own monopile)'),
    F4('USA', 'Coastal Virginia Offshore Wind (CVOW) Commercial Project', 'mp',
       url='https://eew-group.com/projects-references/success-stories/news-detail/coastal-virginia-offshore-wind-project/',
       zh='176 座單樁（最大直徑 9.5 m、1,538 噸），2024–2025 年安裝（3 座海上變電站另以基樁固定）',
       en='176 monopiles (up to 9.5 m across and 1,538 t), installed in 2024–2025 (the three offshore substations stand on pin piles)'),
    F4('USA', 'Revolution Wind', 'mp', url='https://www.oedigital.com/news/513807-boskalis-installs-first-foundation-for-revolution-wind-project-offshore-us',
       zh='65 座加大型（XXL）風機單樁，2024 年 5 月至 2025 年第 2 季安裝（2 座海上變電站另有更大的單樁）',
       en='65 XXL turbine monopiles installed between May 2024 and Q2 2025 (two larger monopiles carry the offshore substations)'),
    # 2026-10-01 第五批（全量查證，子代理搜尋、逐條引文以 check_quotes 核對）· fifth batch, every quote checked
    F5('CHN', 'CGN Huizhou Gangkou I & II', 'jk', url='http://www.news.cn/fortune/2023-12/13/c_1130023531.htm',
       zh='共104座：一期25萬kW（6.45 MW機組）2021-12-28全容量併網，二期75萬kW（PA區10×8.5＋20×12＋9×14 MW等）2023-12-12投產；新華社說該項目「創新研發了具有新型過渡段結構的深水區導管架基礎」，一期招標亦為導管架預製與施工（Ⅲ標段12套預製、20套沉樁施工），2021-07「秦航工2300」在惠州海域吊裝導管架（新華網2023-12-13、國資委2023-12-15、中國能建2023-12-18、中國電力招標網2020-06-27、搜狐2021-07-21）。',
       en='104 turbines in all: phase I 250 MW (6.45 MW units) fully grid-connected 2021-12-28, phase II 750 MW (PA block 10 x 8.5 + 20 x 12 + 9 x 14 MW etc.) commissioned 2023-12-12. Xinhua says the project ’developed a deep-water jacket foundation with a new transition-piece structure’; the phase I tenders were also for jacket prefabrication and installation (lot III: 12 jackets prefabricated, 20 driven) and in July 2021 the crane vessel Qinhanggong 2300 installed jackets in Huizhou waters (Xinhua 2023-12-13, SASAC 2023-12-15, CEEC 2023-12-18, dlztb 2020-06-27, Sohu 2021-07-21).'),
    F5('CHN', 'Guangdong Zhanjiang Xuwen Offshore wind farm', 'mp', url='https://m.gdzjdaily.com.cn/p/2816813.html',
       zh='原場600 MW＝94×6.45 MW，2021-11-26全部併網，報導稱「30天內完成單樁沉樁20根」（湛江日報2021-11-26）；300 MW增容＝25×12 MW，「風機基礎全部採用單樁基礎」（樁徑8.75–9.7 m），2024-12-17全容量併網（搜狐／龍船風電網2023-09-21、2024-07-03，CPEM 2024）。原場94座未見逐場型式說明，僅有單樁沉樁報導。',
       en='Original 600 MW = 94 x 6.45 MW, all grid-connected 2021-11-26, with reports of ’20 monopiles driven in 30 days’ (Zhanjiang Daily 2021-11-26); the 300 MW extension = 25 x 12 MW, ’all turbine foundations are monopiles’ (8.75-9.7 m diameter), fully connected 2024-12-17 (Sohu/Longchuan 2023-09-21 and 2024-07-03, CPEM 2024). No explicit statement covers all 94 original turbines, only the monopile-driving report.'),
    F5('CHN', 'Guoxin Dafeng 850 MW', 'mp', url='http://ddx.gubit.cn/fenxi/002608/202510081600.html',
       zh='100×8.5 MW，「風機基礎全部採用大直徑單樁結構」，2025年完成100根單樁基礎施工，2025-12-29全部風機併網（查股網／交匯點2025-10-08、國資委2026）。',
       en='100 x 8.5 MW; ’all turbine foundations use large-diameter monopiles’, all 100 monopiles driven in 2025 and all turbines grid-connected by 2025-12-29 (gubit/Jiaohuidian 2025-10-08, SASAC 2026).'),
    F5('CHN', 'Shandong Energy Bozhong A', 'mp', url='http://news.bandao.cn/a/620265.html',
       zh='60×8.35 MW（501 MW），全場單樁60根（大金重工製30根、煙台打撈局施工30台單樁基礎，2022-04-16首樁沉樁）（半島網／新華社2022-05-04、搜狐／煙台打撈局2022-04-19）。',
       en='60 x 8.35 MW (501 MW); 60 monopiles for the whole farm (30 made by Dajin Heavy Industry, Yantai Salvage installing 30 monopile foundations; first pile driven 2022-04-16) (Bandao/Xinhua 2022-05-04, Sohu/Yantai Salvage 2022-04-19).'),
    F5('CHN', 'Zhuanghe V', 'mp', url='https://finance.sina.com.cn/jjxw/2025-04-13/doc-inesycqi0944554.shtml',
       zh='招商局太平灣與三峽能源的大連莊河海上風電場址V項目250 MW（24台9MW＋4台8.5MW），風機基礎全部採單樁—摩擦筒結構，2025-03-31基礎全部完工、2025-04-20主體完工（大連天健網／中新網遼寧2025-04-22、新浪財經2025-04-13；中交一航局2025-03-31報導因網站拒絕存取未能抓取）。',
       en='Dalian Zhuanghe site V, 250 MW (24 x 9 MW + 4 x 8.5 MW) by China Merchants Taipingwan and CTG Energy: all turbine foundations are monopile-plus-friction-can structures; foundations finished 2025-03-31, main works 2025-04-20 (Dalian runsky/Chinanews Liaoning 2025-04-22, Sina Finance 2025-04-13; the CCCC First Harbour report of 2025-03-31 could not be fetched).'),
    F5('CHN', 'CGN Yangjiang Nanpeng Island', 'mx', url='https://www.ne21.com/news/show-135824.html', parts=[["jk", 41], ["mp", 32]],
       zh='中廣核陽江南鵬島400 MW（73台5.5MW）：四樁導管架41台、普通大直徑單樁29台、嵌岩單樁3台（合計單樁32台），2020-11-17全部73台基礎完工，2020-12中旬全容量併網（中廣核新能源2020-11-19、陽江廣播電視台2021-01-26，世紀新能源網轉載）。',
       en='CGN Yangjiang Nanpeng Island, 400 MW (73 x 5.5 MW): 41 four-pile jackets, 29 ordinary large-diameter monopiles and 3 rock-socketed monopiles (32 monopiles in total); all 73 foundations finished 2020-11-17, full grid connection mid-December 2020 (CGN New Energy 2020-11-19, Yangjiang TV 2021-01-26, via ne21).'),
    F5('CHN', 'Longyuan Sheyang H2', 'mp', url='http://www.chnenergybidding.com.cn/bidweb/001/001002/001002003/20220126/a64913cb-cf9d-4f39-8a5f-8d3af8011429.html',
       zh='射陽龍源 2022-01 的招標公告（兩案「均已建成投產」）：射陽海上南區 H2# 30 萬千瓦共 67 台機組，全部為單樁基礎；2025-12 江蘇海上龍源的招標也寫「海上射陽風電場風機基礎為單管樁」。',
       en='Sheyang Longyuan’s tender notice of Jan 2022 (both projects “built and in operation”): the Sheyang South H2# 300 MW project has 67 turbines, all on monopiles; a Jiangsu Offshore Longyuan tender of Dec 2025 also says the Sheyang offshore farm’s turbines stand on monopiles.'),
    F5('CHN', 'Jiangsu Sheyang Southern Area H2-1 Offshore wind farm', 'mp', url='http://www.chnenergybidding.com.cn/bidweb/001/001002/001002003/20220126/a64913cb-cf9d-4f39-8a5f-8d3af8011429.html',
       zh='射陽龍源 2022-01 的招標公告（已建成投產）：射陽海上南區 H2-1# 10 萬千瓦共 23 台機組，全部為單樁基礎（與 H2 的 67 台是不同的項目）。',
       en='Sheyang Longyuan’s tender notice of Jan 2022 (built and in operation): the Sheyang South H2-1# 100 MW project has 23 turbines, all on monopiles (a separate project from H2’s 67).'),
    F5('CHN', 'Jiangsu Dafeng H4 Offshore (Longyuan) wind farm', 'mp', url='http://www.chnenergybidding.com.cn/bidweb/001/001002/001002002/20210531/771654d8-ec51-4fea-89a2-375f013b0849.html',
       zh='龍源 2021-05 的招標公告：龍源江蘇大豐 H4# 300 MW 共 47 台機組，全部為單樁基礎；2020 年的基礎施工招標也是 47 台單樁，龍源振華承做「47 基單樁基礎包覆防腐」（2020-09）。',
       en='Longyuan’s tender notice of May 2021: Longyuan Jiangsu Dafeng H4# 300 MW has 47 turbines, all on monopiles; the 2020 foundation tender also covers 47 monopiles, and Longyuan Zhenhua did the anti-corrosion wrapping of the 47 monopiles (Sept 2020).'),
    F5('CHN', 'Jiangsu Dafeng H6 Offshore (Longyuan) wind farm', 'mp', url='http://www.chnenergybidding.com.cn/bidweb/001/001002/001002002/20210531/771654d8-ec51-4fea-89a2-375f013b0849.html',
       zh='龍源 2021-05 的招標公告：龍源江蘇大豐 H6# 300 MW 共 47 台機組，全部為單樁基礎；2020 年的基礎施工招標也是 47 台單樁，另有「H6# 單樁基礎包覆防腐施工工程」（2020-10）。',
       en='Longyuan’s tender notice of May 2021: Longyuan Jiangsu Dafeng H6# 300 MW has 47 turbines, all on monopiles; the 2020 foundation tender also covers 47 monopiles, with a separate monopile anti-corrosion contract (Oct 2020).'),
    F5('CHN', 'Longyuan Dafeng H7', 'mp', url='http://www.chnenergybidding.com.cn/bidweb/001/001002/001002002/20201013/e0f6eaca-cc08-4397-9971-3b547bd65ad9.html',
       zh='龍源鹽城大豐 2020-10 的招標公告（已建成）：二期（H7）共 80 台機組，全部為單樁基礎；海力風電的證監會文件另列韓通與龍源振華兩個「龍源大豐 H7 單樁」供應項目。',
       en='Longyuan Yancheng Dafeng’s tender notice of Oct 2020 (built): phase 2 (H7) has 80 turbines, all on monopiles; Haili Wind’s CSRC filing lists two “Longyuan Dafeng H7 monopile” supply projects (Hantong and Longyuan Zhenhua).'),
    F5('CHN', 'Jiangsu Dafeng H12 Offshore (Longyuan) wind farm', 'mx', url='http://www.chnenergybidding.com.cn/bidweb/001/001002/001002002/20201013/e0f6eaca-cc08-4397-9971-3b547bd65ad9.html', parts=[['mp', 40], ['jk', 40]],
       zh='龍源鹽城大豐 2020-10 的招標公告（H12 於 2017–2018 年建成）：一期（H12）共 80 台機組，其中單樁基礎 40 台、導管架基礎 40 台。',
       en='Longyuan Yancheng Dafeng’s tender notice of Oct 2020 (H12 built 2017–2018): phase 1 (H12) has 80 turbines, 40 on monopiles and 40 on jackets.'),
    F5('CHN', 'CTG Yangjiang Shapa Phase 1', 'mx', url='http://www.yangjiang.gov.cn/yjzrzy/attachment/0/58/58161/731643.pdf', parts=[['mp', 39], ['jk', 13], ['bk', 3]],
       zh='沙扒一期海域使用補充論證報告書（陽江市自然資源局 2023-09 公示，已建項目）：已建 55 台明陽 5.5 MW，風機基礎為 39 台單樁、10 台四樁非嵌岩導管架、3 台單柱複合筒與 3 台吸力桶導管架（原核准的三樁與四樁導管架已調整）。',
       en='Shapa phase 1 supplementary sea-use report (Yangjiang natural resources bureau, Sept 2023, built project): 55 Mingyang 5.5 MW turbines on 39 monopiles, 10 four-pile non-rock-socketed jackets, 3 single-column composite buckets and 3 suction-bucket jackets (the approved tripile and four-pile jacket design was changed).'),
    F5('CHN', 'CTG Yangjiang Shapa Phase 3', 'mx', url='http://www.yangjiang.gov.cn/yjzrzy/attachment/0/58/58158/731643.pdf', parts=[['mp', 22], ['jk', 27], ['pc', 12]],
       zh='沙扒三期海域使用補充論證報告書（陽江市自然資源局 2023-09 公示；2021-12-16 建設完成）：固定式 61 台為 22 台單樁、15 台植入式嵌岩三樁導管架、12 台非嵌岩四樁導管架、12 台高樁承台（每台 6 根樁）；另 1 台漂浮式是本站的「三峽引領號」。',
       en='Shapa phase 3 supplementary sea-use report (Yangjiang natural resources bureau, Sept 2023; completed 16 Dec 2021): the 61 fixed turbines stand on 22 monopiles, 15 implanted rock-socketed three-pile jackets, 12 non-rock-socketed four-pile jackets and 12 high-rise pile caps (six piles each); the one floating unit is the site’s separate “Sanxia Yinling” record.'),
    F5('CHN', 'Putian Shicheng', 'pc', url='https://www.ccccyhj.com/article/96/detail-3233.html',
       zh='29 台（26 台 7 MW＋3 台 6 MW，福建省自然資源廳 2024-05）全為高樁承台：首批風機基礎施工標段共 10 座承台（世紀新能源網，2020-01），Ⅱ 標段 19 台高樁承台（中交一航局，2021-03），10＋19＝29；CPEM 轉載研報也寫石城採用高樁承台式結構。',
       en='All 29 turbines (26 × 7 MW + 3 × 6 MW, Fujian natural resources department, May 2024) stand on high-rise pile caps: the first foundation lot has 10 caps (ne21, Jan 2020) and lot II 19 high-rise caps (CCCC First Harbour, Mar 2021), 10 + 19 = 29; a research note reprinted by CPEM also says Shicheng uses high-rise pile caps.'),
    F5('CHN', 'CTG Yangjiang Shapa Phase 4', 'mx', url='http://www.yangjiang.gov.cn/yjzrzy/attachment/0/58/58159/731643.pdf', parts=[['mp', 7], ['jk', 36]],
       zh='43 部東方 7 MW：7 座單樁＋36 座非嵌岩四樁導管架（沙扒四期海域使用補充論證報告書，陽江市自然資源局 2023-09 公示；2020-04 開工、2021-12 建設完成，'
          '原核准的 6 單樁＋14 單柱複合筒＋27 嵌岩高樁承台已調整）。',
       en='43 Dongfang 7 MW turbines: 7 monopiles + 36 non-rock-socketed four-pile jackets (Shapa phase 4 supplementary sea-use report, Yangjiang natural resources bureau, '
          'Sept 2023; built Apr 2020 – Dec 2021; the approved 6 monopiles + 14 composite buckets + 27 rock-socketed pile caps were changed).'),
    F5('CHN', 'CTG Yangjiang Shapa Phase 5', 'mx', url='http://www.yangjiang.gov.cn/yjzrzy/attachment/0/58/58160/731643.pdf', parts=[['pc', 11], ['jk', 23], ['bk', 13]],
       zh='47 部 6.45 MW：高樁承台 11、導管架 23（非嵌岩 14、芯柱式嵌岩 5、吸力桶 4）、單柱複合筒 13（含 4 座需加配重）（沙扒五期海域使用補充論證報告書，陽江市自然資源局 2023-09 公示，已建項目）。',
       en='47 × 6.45 MW: 11 high-rise pile caps, 23 jackets (14 non-rock-socketed, 5 core-column rock-socketed, 4 suction-bucket) and 13 single-column composite buckets '
          '(4 of them ballasted) (Shapa phase 5 supplementary sea-use report, Yangjiang natural resources bureau, Sept 2023, built project).'),
    F5('CHN', 'CTG Yangjiang Shapa Phase 2', 'jk', url='https://www.ne21.com/news/show-166702.html',
       zh='三峽陽江沙扒二期400 MW（62台6.45MW，水深28–32 m），2021-11-27全部機組投產。基礎為導管架：項目設計四樁非嵌岩導管架、芯柱式嵌岩三樁導管架、植入式嵌岩導管架多種型式（三峽新能源2020-08-31），投產報導稱完成國內首個大直徑非嵌岩四樁導管架與芯柱嵌岩三樁導管架施工（三峽能源珠江公司2021-11-29，世紀新能源網轉載）。各型式座數未查到。',
       en='CTG Yangjiang Shapa phase 2, 400 MW (62 x 6.45 MW, 28–32 m water depth), all units in operation 2021-11-27. Jacket foundations: the project designed four-pile non-rock-socketed jackets, core-pile rock-socketed three-pile jackets and implanted rock-socketed jackets (CTG New Energy 2020-08-31); the commissioning report cites China’s first large-diameter non-rock-socketed four-pile jackets and core-pile rock-socketed three-pile jackets (CTG Energy Pearl River 2021-11-29, via ne21). Counts per jacket type not found.'),
    F5('CHN', 'Liaoning Dalian Zhuanghe 4 Area I Offshore wind farm', 'mp', url='https://news.qq.com/rain/a/20210702A0AYV400',
       zh='51 台（26×7.5 MW＋25×6.2 MW，惠生海工）；中新網 2021-07-02：單根鋼管樁（頂徑 6.5 m、底徑 7.2 m、長 78 m、1080 t）即為 2 號機位的基礎結構，為大直徑單樁；2021-12-29 全容量併網（新華網）。新華網另註明吸力桶導管架用於 Ⅱ 風場，非 Ⅳ1。',
       en='51 turbines (26 x 7.5 MW + 25 x 6.2 MW, Wison). China News 2021-07-02: a single steel pile (6.5 m top, 7.2 m bottom, 78 m, 1,080 t) is the foundation of turbine no. 2, i.e. a large-diameter monopile; full grid connection 2021-12-29 (Xinhua). Xinhua notes the suction-bucket jackets were used at site II, not IV-1.'),
    F5('CHN', 'Shanghai Jinshan Offshore wind farm', 'mp', url='https://www.cweea.com.cn/xwdt/html/40620.html',
       zh='36 根單樁基礎、36 台 8.5 MW（中交三航局施工內容，風能產業網 2025）；2025-09-23 全容量併網（人民網上海 2025-09-25）。',
       en='36 monopile foundations for 36 x 8.5 MW turbines (CCCC Third Harbour scope, cweea.com.cn 2025); full grid connection 2025-09-23 (People’s Daily Shanghai, 2025-09-25).'),
    F5('CHN', 'Guangdong Yangjiang Nanpengdao (China Energy Conservation) Offshore wind farm', 'jk', url='https://www.cecep.cn/cecep/news/xsqydt/2025/6/phoneI1384972707912744960.html',
       zh='55 台 5.5 MW 全部採四樁導管架（中國節能集團 2025-06；新浪財經轉陽江日報 2023）；2021-11 全容量投產。',
       en='All 55 x 5.5 MW turbines on four-pile jackets (CECEP group, June 2025; Sina citing Yangjiang Daily, 2023); fully commissioned Nov 2021.'),
    F5('CHN', 'Zhejiang Shengsi 5, 6 Offshore wind farm', 'pc', url='http://www.offshorecable.com.cn/news/show.php?itemid=17825',
       zh='中廣核嵊泗5#6#：45 台 6.25MW 風機全部採八樁高樁承台基礎，360 根鋼管樁 2021-02-02 沉樁收官（中廣核新能源稿，中國海上風電網 2021-02-03）。',
       en='CGN Shengsi 5/6: all 45 × 6.25 MW turbines on eight-pile high-rise pile-cap foundations; the 360th and last pile was driven on 2021-02-02 (CGN New Energy release via offshorecable.com.cn, 2021-02-03).'),
    F5('CHN', 'Guodian Zhoushan Putuo 6#2', 'pc', url='https://www.ceic.com/gjnyjtww/chnyxfc/202006/e5a14799afc44f2a890f4e1784673ac0.shtml',
       zh='國電電力舟山普陀6號2區：63 台西門子 4MW 風機採「高樁高承台改進型」基礎，2019-04 全部併網（國家能源集團 2020-06）。',
       en='Guodian Power Zhoushan Putuo 6 Zone 2: 63 Siemens 4 MW turbines on an improved high-pile high-cap foundation, fully grid-connected April 2019 (CHN Energy, June 2020).'),
    F5('CHN', 'Guangdong Energy Zhanjiang Wailuo Phase 1', 'mp', url='http://www.sasac.gov.cn/n2588025/n2588124/c11303731/content.html',
       zh='粵電湛江外羅 198MW：36 台 5.5MW，36 根大直徑單樁 2019-05-20 全部沉樁完成（中國能建稿，國資委 2019-05-28）。',
       en='Guangdong Energy Zhanjiang Wailuo 198 MW: 36 × 5.5 MW turbines, all 36 large-diameter monopiles driven by 2019-05-20 (China Energy Engineering release via SASAC, 2019-05-28).'),
    F5('CHN', 'Guoneng Dafeng H5', 'mp', url='https://www.ne21.com/news/show-155282.html',
       zh='32台GW184-6.45MW、206.4MW，風機基礎全部採無過渡段單樁（華電重工／世紀新能源網 2021-01-05；大豐區政府 2024-12）；2021年12月全容量併網（江蘇省國資委 2022-04）。',
       en='32 x GW184-6.45 MW, 206.4 MW; all turbine foundations are monopiles without transition piece (Huadian Heavy Industries via ne21.com, 5 Jan 2021; Dafeng district government, Dec 2024); full grid connection Dec 2021 (Jiangsu SASAC, Apr 2022).'),
    F5('CHN', 'Guangdong Energy Zhanjiang Wailuo Phase 2', 'mp', url='https://www.ne21.com/news/show-165743.html',
       zh='200MW、32台6.25MW機組，採大直徑單樁基礎（樁重817t、長64m），2021-09-06全部吊裝完成（世紀新能源網 2021-09）。',
       en='200 MW, 32 x 6.25 MW turbines on large-diameter monopiles (817 t, 64 m); all 32 installed by 6 Sep 2021 (ne21.com, Sep 2021).'),
    F5('CHN', 'Jiangsu Dongtai Zhugensha H1 Offshore wind farm', 'mp', url='http://www.bioffshore.com/news/1.html',
       zh='國華竹根沙H1# 200MW、50台4.0MW，風機基礎鋼管樁全由泰勝藍島承製，2021-05-04最後一套單樁交付（南通泰勝藍島 2021-05-08）。',
       en='Guohua Zhugensha H1#: 200 MW, 50 x 4.0 MW; all turbine foundation piles built by Taisheng Landao, the last monopile delivered on 4 May 2021 (Nantong Taisheng Landao, 8 May 2021).'),
    F5('CHN', 'Donghai Bridge Phase II', 'pc', url='https://www.geoseu.cn/yanjiuyuan/5136.html',
       zh='二期 28 台（27 台上海電氣 3.6MW＋1 台華銳 5MW）2015 年 2 月 12 日併網（澎湃新聞 2019）；鑒衡認證專文（geoseu.cn）指東海大橋風電場全場 20.4 萬千瓦、安裝 3.0MW 與 5.0MW 機組，採用斜高樁承台基礎。',
       en='Phase II’s 28 units (27 x Sewind 3.6 MW + 1 x Sinovel 5 MW) were grid-connected on 12 Feb 2015 (The Paper, 2019); the CGC certification article on geoseu.cn states the whole 204 MW Donghai Bridge farm (3.0 MW and 5.0 MW units) uses inclined high-pile concrete cap foundations.'),
    F5('CHN', 'Shanghai Lingang Demonstration Phase 1', 'pc', url='https://www.fegroup.com.cn/ydkg/xwzx79/gsxw10/577818/index.html',
       zh='一期示範項目 25 台 4MW（上海電氣 W4000）全部採用高樁承台：遠東集團 2019 年報導「從沉樁、承台澆築到完成全部 25 台風機安裝」，2018 年 5 月 8 日開工、主體 238 天完成。',
       en='The 25 x 4 MW (Sewind W4000) Phase 1 demonstration project used high-pile concrete caps: Far East Group (2019) reports ’from pile driving and cap pouring to installing all 25 turbines’ in 238 days after the 8 May 2018 start.'),
    F5('CHN', 'Shanghai Lingang Demonstration Phase 2', 'pc', url='https://www.cnssce.org/38/201806/2127.html',
       zh='二期 28 部 3.6 MW（100.8 MW）的風機基礎為高樁混凝土承台，每座 8 根斜鋼管樁沿直徑 10 m 圓周布置（施工單位中交三航局科研院 2018 年承台混凝土控裂論文，上海市土木工程學會）。',
       en='The 28 × 3.6 MW (100.8 MW) Phase 2 turbines stand on high-rise concrete pile caps, each on eight raked steel piles spaced around a 10 m circle (2018 crack-control paper by the contractor, CCCC Third Harbour’s research institute, Shanghai Society of Civil Engineering).'),
    F5('CHN', 'SPIC Binhai North H1', 'mp', url='https://www.ceeia.com/QYDT/d/201711/71378.html',
       zh='25 台西門子 4MW 全部採用 6m 以上超大直徑無過渡段單樁（國內首次），2015 年 10 月 3 日開工、2016 年 6 月 6 日整體投運（中國電器工業協會 2017 年 11 月，轉載國家優質工程金獎報導）。',
       en='All 25 Siemens 4 MW units stand on >6 m diameter transition-piece-free monopiles (a first in China); construction 3 Oct 2015 to full operation 6 Jun 2016 (CEEIA, Nov 2017, on the National Quality Engineering Gold Award).'),
    F5('CHN', 'Fuqing Xinghua Bay Phase 1 (demo)', 'pc', url='https://www.geoseu.cn/yanjiuyuan/5136.html',
       zh='樣機試驗風場 14 台（7 家廠商，5–6.7MW，共 79.4MW）全部採用大直徑直高樁承台基礎（鑒衡認證專文，geoseu.cn；水深 5–16m、淺覆蓋層）。',
       en='All 14 prototype units (7 makers, 5-6.7 MW, 79.4 MW) stand on large-diameter vertical high-pile concrete caps (CGC certification article on geoseu.cn; 5-16 m water, shallow overburden).'),
    F5('VNM', 'Bến Tre 10 Bình Đại 1 Offshore wind farm', 'mp', url='https://nangluongvietnam.vn/khoi-cong-lap-dat-cac-tru-mong-du-an-dien-gio-ngoai-khoi-binh-dai-25662.html',
       zh='Gulf 旗下湄公風電平大風場：2020-11 開工打設單樁（越南首個 monopile 專案）；PTSC PPS 2023 年基礎檢查資料寫全場 31 座、單樁直徑 5.5 m、總容量 128 MW。',
       en='Gulf’s Mekong Wind Power Binh Dai farm: monopile installation began Nov 2020 (first monopile project in Vietnam); PTSC PPS 2023 foundation-inspection notice gives 31 turbines on 5.5 m monopiles for the 128 MW plant.'),
    F5('VNM', 'Thanh Hải No. 5 Offshore wind farm', 'pc', url='https://www.evn.com.vn/d6/news/Khanh-thanh-Nha-may-dien-gio-so-5-Thanh-Hai-Ben-Tre-100-668-55952.aspx',
       zh='新環球檳椥（Tân Hoàn Cầu Bến Tre）5號風場：成海1–4 共 28 座、120 MW（EVN 2022-07）；黎蒂建設負責「打設 D800 預應力混凝土樁並完成基礎」，一期 7 座、二期 21 座，即 PHC 群樁＋承台。',
       en='Tan Hoan Cau Ben Tre’s No. 5 farm (Thanh Hai 1–4, 28 turbines, 120 MW per EVN, Jul 2022): contractor Le Thy drove D800 prestressed concrete piles and finished the foundations for phase 1 (7 units) and phase 2 (21 units), i.e. PHC pile group with cap.'),
    F5('VNM', 'Dong Hai 1 – Tra Vinh (Trungnam)', 'pc', url='https://bactrungnam-vn.com/nha-may-dien-gio-dong-hai-1-v7-1-2/',
       zh='中南集團茶榮東海1號 25 座：分包商北中南建設說明基礎為預應力離心混凝土樁（每座 34 支 D1000 或 44 支 D800）加鋼筋混凝土承台，2021-02～07 施工。',
       en='Trungnam’s Dong Hai 1 (Tra Vinh), 25 turbines: subcontractor Bac Trung Nam states foundations are prestressed spun concrete piles (34×D1000 or 44×D800 per foundation) with a reinforced-concrete cap, built Feb–Jul 2021.'),
    F5('VNM', 'Tan Phu Dong 1 (Tien Giang, GEC)', 'pc', url='https://lethycorp.com/en/du-an-da-thi-cong/tan-phu-dong-1-html',
       zh='GEC 新富東1號 24 座（PC1 EPC，2022-10 裝完最後一座）：黎蒂建設承做 PHC D800 樁打設，建設雜誌 2022-05 報導 24 座基礎供應混凝土，即 PHC 群樁＋承台。',
       en='GEC’s Tan Phu Dong 1, 24 turbines (PC1 EPC, last turbine Oct 2022): Le Thy drove PHC D800 piles for the turbine foundations and Tap chi Xay dung (May 2022) reports concrete supply for 24 foundations, i.e. PHC pile group with cap.'),
    F5('VNM', 'Dong Hai 1 Offshore wind farm', 'pc', url='https://plc-corp.vn/cong-ty-thi-cong-dong-coc-tren-bien.html',
       zh='北方能源薄寮東海1號 26 座 Vestas V150-4.0（一期 13＋二期 13）：PLC 公司說明在薄寮東海1號與和平1、2 打設 63–76 m 超長 PHC D800 樁作風機基礎，即 PHC 群樁＋承台。',
       en='Bac Phuong’s Dong Hai 1 (Bac Lieu), 26 Vestas V150-4.0 (13+13): piling contractor PLC states it drove 63–76 m PHC D800 piles for the turbine foundations at Dong Hai 1 and Hoa Binh 1 & 2 in Bac Lieu, i.e. PHC pile group with cap.'),
    F5('VNM', 'Tan Thuan (PECC2) Phase 1+2', 'pc', url='https://www.phanvu.vn/truyen-thong/tin-hoat-dong/dien-gio-tan-thuan-chao-mung-25-nam-ngay-thanh-lap-phan-vu',
       zh='金甌新順 75 MW、18 座（PECC2 EPC，2021-10-30 COD）：潘武集團承做全部 18 座的混凝土樁打設與承台，2021-05 樁全部完成，即混凝土群樁＋承台。',
       en='Tan Thuan 75 MW, 18 turbines (PECC2 EPC, COD 30 Oct 2021): Phan Vu supplied and drove the concrete piles and finished the caps for all 18 foundations, piling complete May 2021, i.e. concrete pile group with cap.'),
    F5('VNM', 'Hiep Thanh (Tra Vinh)', 'mp', url='https://offshorewind.biz/2021/08/27/all-foundations-installed-at-vietnams-hiep-thanh-and-tra-vinh-v1-2-nearshore-wind-farms',
       zh='協成 18 部西門子歌美颯 4.3 MW：廣州打撈局 2021 年 8 月完成協成與茶榮 V1-2 兩場「全部單樁基礎」的安裝（offshoreWIND.biz 2021-08-27）。',
       en='Hiep Thanh, 18 Siemens Gamesa 4.3 MW: Guangzhou Salvage Bureau finished installing "all monopile foundations" at Hiep Thanh and Tra Vinh V1-2 in August 2021 (offshoreWIND.biz, 27 Aug 2021).'),
    F5('VNM', 'Hoa Binh 1 Phase 1', 'pc', url='https://plc-corp.vn/cong-ty-thi-cong-dong-coc-tren-bien.html',
       zh='方英集團和平1號一期 13 座 Vestas（2021-07-02 送電）：PLC 與 Vinaincon 均記載和平1、2 風機基礎為 PHC D500C／D800C 預應力離心混凝土樁，即群樁＋承台。',
       en='Phuong Anh’s Hoa Binh 1 phase 1, 13 Vestas turbines (energised 2 Jul 2021): PLC and Vinaincon both record PHC D500C/D800C prestressed spun concrete piles for the Hoa Binh 1 & 2 turbine foundations, i.e. pile group with cap.'),
    F5('VNM', 'Hoa Binh 1 Phase 2', 'pc', url='https://plc-corp.vn/cong-ty-thi-cong-dong-coc-tren-bien.html',
       zh='和平1號二期 13 座（和平1號二期＋和平2號共 26 座，2021-08-05 送電；業主方英集團）：基礎同一期，PHC 預應力混凝土樁群＋承台。',
       en='Hoa Binh 1 phase 2, 13 turbines (26 turbines across HB1-II and HB2, energised 5 Aug 2021; owner Phuong Anh): same PHC prestressed concrete pile-group foundations as phase 1.'),
    F5('VNM', 'Hoa Binh 2', 'pc', url='https://plc-corp.vn/cong-ty-thi-cong-dong-coc-tren-bien.html',
       zh='和平2號 13 座（2021-09-15 送電，和平1、2 共 39 座；業主方英集團）：PHC 預應力混凝土樁群＋承台。',
       en='Hoa Binh 2, 13 turbines (energised 15 Sep 2021; 39 turbines across Hoa Binh 1 & 2; owner Phuong Anh): PHC prestressed concrete pile group with cap.'),
    F5('VNM', 'V1-2 Truong Long Hoa (Tra Vinh)', 'mp', url='https://www.ttvngroup.vn/en/hoa-hoi-solar-power-plant-and-v1-2-wind-power-plant-owned-by-the-joint-venture-of-ttvn-group-and-thailand-partners-awarded-as-2021typical-renweable-energy-project/',
       zh='V1-2 48 MW、12 座：長城越南集團（TTVN）與企業論壇報 2021 年記載採 5.5 m 直徑鋼製單樁（monopile）以法蘭螺栓接塔，12/12 全部完成。',
       en='V1-2, 48 MW, 12 turbines: TTVN Group and Dien dan Doanh nghiep (2021) record 5.5 m diameter steel monopiles bolted to the tower via a flange, all 12 erected.'),
    F5('VNM', 'V1-3 Truong Long Hoa 48 MW (REE, Tra Vinh No.3)', 'pc', url='https://vssmge.org/thiet-ke-va-thi-cong-mong-tru-dien-gio-tai-cac-du-an-cua-fecon/',
       zh='REE 茶榮 V1-3 48 MW：FECON 承做 PHC D800C／D500C 樁與風機基礎，越南土力學會論文列「12 móng cọc PHC（D m = 21,5 m）」，即 PHC 群樁＋承台。',
       en='REE’s Tra Vinh V1-3, 48 MW: FECON drove PHC D800C/D500C piles and built the turbine foundations; the VSSMGE paper lists 12 PHC pile foundations (21.5 m cap diameter), i.e. PHC pile group with cap.'),
    F5('VNM', 'V1-1 Truong Long Hoa (Tra Vinh)', 'pc', url='https://www.energyglobal.com/wind/03012020/vestas-wins-epc-contract-in-vietnam/',
       zh='韓國－茶榮一期 12 部 Vestas V150-4.2：Vestas 統包合約寫風機裝在「架高於海面、以多樁支撐」的強化基座上、以引橋連岸，即群樁＋承台；'
          'VIR 2020-09 寫 12 座風機基礎與 4.2 km 引橋已成形，潘武集團供應 D500／D600／D800 預應力混凝土樁給土建承包商 Khang Đức（投資報落成報導）。',
       en='Korea–Tra Vinh phase 1, 12 Vestas V150-4.2: Vestas’ turnkey contract says the turbines sit on reinforced foundations "raised above sea level on multi-pile structures" '
          'and linked to shore by bridges, i.e. a pile group with a cap; VIR (Sept 2020) reports the 12 turbine foundations and a 4.2 km access bridge in place, and Phan Vu supplied '
          'D500/D600/D800 prestressed concrete piles to the civil contractor Khang Duc (Bao Dau tu inauguration report).'),
    F5('VNM', 'Soc Trang 7 Phase 1', 'pc', url='https://baoxaydung.vn/ngam-canh-dong-dien-gio-tren-bien-soc-trang-192240422101537121.htm',
       zh='春球朔莊7號一期 7 座 4.2 MW（2021-10 運轉）：建設報 2024-04 寫「多樁基礎，每座由 40 支混凝土樁組成」，即混凝土群樁＋承台。',
       en='Xuan Cau’s Soc Trang No. 7 phase 1, 7 × 4.2 MW (operating since Oct 2021): Bao Xay dung (Apr 2024) reports multi-pile foundations with 40 concrete piles per turbine, i.e. concrete pile group with cap.'),
    F5('VNM', 'VPL Ben Tre (Nexif Ben Tre 1)', 'pc', url='https://www.phanvu.vn/en-US/vpl-ben-tre-wind-power-plant-p1',
       zh='VPL 檳椥一期 30 MW（平大縣淺水區）：潘武集團供應 D800C 離心混凝土樁（客戶陸路3公司），即混凝土群樁＋承台；座數未查到。',
       en='VPL Ben Tre phase 1, 30 MW (shallow water, Binh Dai): Phan Vu supplied D800C spun concrete piles (client Lung Lo 3), i.e. concrete pile group with cap; turbine count not found.'),
    F5('CHN', 'CTG Fujian Changle Waihai A', 'jk', url='https://www.thepaper.cn/newsDetail_forward_9187135',
       zh='37座風機全部為套管（導管架），分四樁導管架與吸力式導管架兩種：中鐵大橋局2020年9月安裝國內首台深水四樁導管架，泰勝藍島承製A區10MW四樁導管架，全場風機基礎鋼管樁直徑僅3.0–3.5 m（導管架樁），未見單樁；中鐵大橋局2021年11月寫A區「有四樁導管架、吸力式導管架」，3天吊裝5座深水吸力式導管架，惠生海工也交付A、C區共11座三筒吸力樁導管架（各種座數未查到）；37台＝6.7MW×14＋8MW×13＋10MW×10（澎湃新聞2020-09-15、世紀新能源網2020-11-20、2021-05、百家號2021-11、惠生海工）。',
       en='All 37 turbines on jackets, of two kinds, four-pile and suction-bucket: CRBBG installed China’s first deep-water four-pile jacket here in Sep 2020, Taisheng Lando built the 10 MW four-pile jackets, and all A-area foundation piles are only 3.0–3.5 m in diameter (jacket piles); CRBBG wrote in Nov 2021 that area A “has four-pile jackets and suction jackets”, lifting 5 deep-water suction jackets in 3 days, and Wison delivered 11 three-bucket suction jackets for areas A and C (the count of each kind was not found); 37 turbines = 14×6.7 MW + 13×8 MW + 10×10 MW (The Paper 2020-09-15, ne21 2020-11-20 and 2021-05, Baijiahao 2021-11, Wison).'),
    F5('CHN', 'Fuqing Haitan Strait', 'pc', url='https://www.ne21.com/news/show-160542.html',
       zh='46座風機全部採嵌岩高樁承台（六樁直樁高樁承台）：華電重工2021-04-16完成46個機位全部沉樁，2021-10-02全部吊裝，2021-11-18全部並網（世紀新能源網2021-04-30、2021-10-09；廣東省水力和新能源發電工程學會轉中國電力新聞網2021-11-22）。',
       en='All 46 turbines on rock-socketed high-pile caps (six vertical piles): Huadian Heavy Industry finished piling at all 46 positions on 2021-04-16, all turbines installed 2021-10-02 and grid-connected 2021-11-18 (ne21 2021-04-30 and 2021-10-09; GDSHE repost of China Electric Power News 2021-11-22).'),
    F5('CHN', 'Guangdong Energy Zhuhai Jinwan', 'mp', url='https://kb.southcn.com/kb/d69d07d3be.shtml',
       zh='55台5.5MW全部採單樁（單根鋼管樁，直徑7.5–8.5 m，最重1470 t），2020-05-16完成最後一座基礎沉樁，2021-04-02全部55台並網（南方網2020-05-17、廣東省國資委2021-04-07）。',
       en='All 55×5.5 MW turbines on monopiles (single steel pipe pile, 7.5–8.5 m diameter, up to 1,470 t); last foundation driven 2020-05-16, all 55 turbines grid-connected 2021-04-02 (Southcn 2020-05-17, Guangdong SASAC 2021-04-07).'),
    F5('CHN', 'Guangdong Yangjiang Shaba (Guangdong Energy) Offshore wind farm', 'jk', url='https://www.ne21.com/news/show-134345.html',
       zh='47台（46台6.45MW＋1台5.5MW，中新網2021-08-31）全為導管架類基礎：A標段（廣東火電）為嵌岩與非嵌岩四樁導管架，B標段（中鐵大橋局）含植入式嵌岩三樁導管架，另有三桶吸力樁型式；2021-08-31全部風機基礎完工（世紀新能源網2020-05；中新網／微信轉載，後者無法機器核對）。各型式座數未查到。',
       en='47 turbines (46×6.45 MW + 1×5.5 MW, China News 2021-08-31), all on jacket-type foundations: lot A (Guangdong Thermal Power) used rock-socketed and non-socketed four-pile jackets, lot B (CRBBG) includes implanted rock-socketed three-pile jackets, plus a three-bucket suction type; all foundations finished 2021-08-31 (ne21 May 2020; China News via WeChat, not machine-checkable). Per-type counts not found.'),
    F5('CHN', 'SPIC Binhai South H3', 'mp', url='https://baijiahao.baidu.com/s?id=1686861092320507372&wfr=spider&for=pc',
       zh='75台4.0MW，全部採用直徑5.5–7m無過渡段鋼管樁（單樁）基礎；2020年12月9日75根樁全部沉樁完成，2020年12月底建成投產。來源：全國能源信息平台（百家號）2020-12、國家電投江蘇公司（ne21 轉載）2022-01-18。',
       en='75 x 4.0 MW, all on 5.5–7 m transition-piece-free steel monopiles; all 75 piles driven by 9 Dec 2020, commissioned end of Dec 2020. Sources: National Energy Information Platform (baijiahao) Dec 2020, SPIC Jiangsu via ne21 2022-01-18.'),
    F5('CHN', 'Jiangsu Rudong H14 (Guangheng) Offshore wind farm', 'mp', url='https://news.96189.com/w/2008/ebbbbcec80b94ed8a6b9441a968e997c.html',
       zh='如東H14為魯能新能源（中國綠發）200MW、50台4MW上海電氣機組，50根單樁基礎於2020年8月全部完工（亞洲首次大直徑單樁浮運沉樁），2020年12月全場並網。來源：南通發布（96189）2020-08-29、電力科技網 2020-07-31、新華網 2023-08-17。',
       en='Rudong H14 is Luneng New Energy (China Green Development)’s 200 MW farm with 50 x 4 MW Shanghai Electric turbines; all 50 monopiles finished Aug 2020 (Asia’s first floated large-diameter monopile), fully grid-connected Dec 2020. Sources: Nantong Fabu via 96189 2020-08-29, eptchina 2020-07-31, Xinhua 2023-08-17.'),
    F5('CHN', 'Huaneng Sheyang H1 / Yancheng', 'mp', url='https://baijiahao.baidu.com/s?id=1663862963857905743&wfr=spider&for=pc',
       zh='華能射陽海上南區H1#300MW：67台風機，67根單樁基礎於2020年4月1日全部沉樁完成（華電重工承建其中37根），2020年11月1日67台全部吊裝完成。來源：中國華能（百家號）2020-04、中國縣域經濟報（百家號）2020-11-05。',
       en='Huaneng Sheyang South H1 300 MW: 67 turbines, all 67 monopiles driven by 1 Apr 2020 (37 of them by Huadian Heavy), all 67 turbines installed 1 Nov 2020. Sources: China Huaneng (baijiahao) Apr 2020, China County Economy News (baijiahao) 2020-11-05.'),
    F5('CHN', 'Zhejiang Energy Jiaxing 1', 'mx', url='https://news.qq.com/rain/a/20211121A08Z6200', parts=[["pc", 37], ["mp", 37]],
       zh='301.2MW、74台：37台採多樁（8根1.6m鋼樁的高樁承台）基礎、37台採單樁基礎，共333根樁；2019年10月7日開始打樁，2021年10月29日74台吊裝完成，2021年11月21日全容量並網。來源：錢江晚報／潮新聞（騰訊）2021-11-21、浙江在線 2021-11-22、浙江省國資委（國資委網）2021-11-23。',
       en='301.2 MW, 74 turbines: 37 on multi-pile (8 x 1.6 m steel piles, high-pile cap) foundations and 37 on monopiles, 333 piles in total; piling from 7 Oct 2019, all 74 turbines installed 29 Oct 2021, full capacity 21 Nov 2021. Sources: Qianjiang Evening News via Tencent 2021-11-21, zjol 2021-11-22, Zhejiang SASAC 2021-11-23.'),
    F5('CHN', 'Zhejiang Daishan 4 Offshore wind farm', 'pc', url='https://baijiahao.baidu.com/s?id=1671060059350234305&wfr=spider&for=pc',
       zh='中廣核浙江岱山4#為234MW、54台（西區18台4MW、東區36台4.5MW），全場採高樁承台基礎（八樁，鋼管樁直徑1.6m；一期50台承台2020年7月澆築完成，西區144根樁2019年5月31日沉樁完成），2020年12月25日54台全容量投產。來源：全國能源信息平台（百家號）2020-07-02、浙江日報（百家號）2019-06-06、人民網浙江 2020-12-28、讀特 2020-12-25。',
       en='CGN Zhejiang Daishan 4 is 234 MW, 54 turbines (18 x 4 MW west, 36 x 4.5 MW east), all on high-pile cap foundations (8 piles of 1.6 m; 50 caps of phase 1 poured by Jul 2020, 144 west-zone piles driven by 31 May 2019); 54 turbines at full capacity 25 Dec 2020. Sources: National Energy Information Platform (baijiahao) 2020-07-02, Zhejiang Daily (baijiahao) 2019-06-06, people.cn Zhejiang 2020-12-28, dutenews 2020-12-25.'),
    F5('CHN', 'SPIC Dafeng H3', 'mp', url='http://www.hhi.com.cn/webfront/webpage/web/contentPage/id/d9cce3cb2d854c7aa1568d2539cbf481',
       zh='大豐H3#300MW（302.4MW，72台4.2MW）由華電重工承建，合同即為「單樁與海上升壓站基礎施工」；2018年9月已完成65根單樁，同年10月22日全部72根單樁完成（東方風力發電網／北極星，無法抓取）；2018年12月20日全容量投產。來源：華電科工官網 2018-09-19、國家電投江蘇公司（ne21 轉載）2022-01-18。',
       en='Dafeng H3 300 MW (302.4 MW, 72 x 4.2 MW), built by Huadian Heavy Industry under a contract for ’monopile and offshore substation foundation construction’; 65 monopiles done by Sept 2018, all 72 reported done on 22 Oct 2018 (eastwp/bjx, not fetchable); full capacity 20 Dec 2018. Sources: HHI 2018-09-19, SPIC Jiangsu via ne21 2022-01-18.'),
    F5('CHN', 'Guohua Dongtai IV (H2)', 'mx', url='http://www.chnenergybidding.com.cn/bidweb/001/001002/001002001/20260427/5666b061-4080-431f-bdac-89b7a31d373c.html',
       parts=[['mp', 73], ['pc', 2]],
       zh='75 台（上海電氣 4.0 MW 63 台、遠景 4.2 MW 12 台）：國家能源集團 2026-04 的招標公告寫「47#、66# 風機為高樁承台，其他為單樁基礎」，即 73 座單樁＋2 座高樁承台。'
          '先前的出處：2019-07-16「16 號單樁沉樁結束，單樁基礎施工宣告完成」（東台市委宣傳部）；2019 年 12 月全部併網（澎湃／國家能源集團）。',
       en='75 turbines (63 Shanghai Electric 4.0 MW and 12 Envision 4.2 MW): CHN Energy’s April 2026 tender notice says units 47# and 66# stand on high-rise pile caps and the rest on monopiles, '
          'i.e. 73 monopiles + 2 high-rise pile caps. Earlier sources: on 16 Jul 2019 “monopile no. 16 completed and monopile foundation works finished” (Dongtai propaganda dept); all units grid-connected in Dec 2019 (The Paper / CHN Energy).'),
    F5('CHN', 'Huaneng Guanyun', 'mp', url='https://jsnews.jschina.com.cn/lyg/a/201910/t20191016_2407402.shtml',
       zh='一期300MW、48台（46台6.45MW＋2台3MW），風機基礎為單樁（2019年10月已完成10根單樁沉樁），2021年6月29日48台全部吊裝，2021年7月30日全容量並網。單樁全數完成的紀錄未抓到。來源：中國江蘇網 2019-10-16、風能產業網（CWEEA）2021-07-05、華能國際（中證網）2021。',
       en='Phase 1: 300 MW, 48 turbines (46 x 6.45 MW + 2 x 3 MW) on monopiles (10 monopiles driven by Oct 2019); all 48 installed 29 Jun 2021, full capacity 30 Jul 2021. A record of all monopiles completed was not fetched. Sources: jschina 2019-10-16, CWEEA 2021-07-05, Huaneng Power Intl via cs.com.cn 2021.'),
    F5('CHN', 'Huaneng Dafeng', 'mp', url='https://baijiahao.baidu.com/s?id=1642946831276885180&wfr=spider&for=pc',
       zh='華能江蘇大豐300MW（毛竹沙海域，離岸55km）分標段施工：中天海洋工程標段共沉樁31根（5MW級單樁，2019年8月完成）；中交一航局Ⅰ標段33根鋼管樁、34台風機（2019年8月20日沉樁完成，9月29日最後一台吊裝並網）。兩標段皆為單樁／鋼管樁，但全場機組總數與是否尚有其他標段未查得。來源：中天科技（百家號）2019、中交一航局（澎湃）2019。',
       en='Huaneng Jiangsu Dafeng 300 MW (Maozhusha, 55 km offshore) was built in lots: Zhongtian Marine drove 31 piles (5 MW-class monopiles, done Aug 2019); CCCC First Harbour’s Lot I had 33 steel piles and 34 turbines (piling done 20 Aug 2019, last turbine 29 Sep 2019). Both lots are monopiles, but the total turbine count and whether other lots exist could not be verified. Sources: Zhongtian (baijiahao) 2019, CCCC FHEC via thepaper 2019.'),
    F5('CHN', 'CGN Rudong Demonstration', 'mp', url='http://china.cnr.cn/gdgg/20160908/t20160908_523123451.shtml',
       zh='38台、152MW，2016-09全場投運；採可拆卸穩樁平台浮吊沉樁，首個深水區無過渡段單樁（央廣網 2016-09-08；中國電器工業協會轉新華網 2016-09-14）；來源未明說38座全為單樁。',
       en='38 turbines, 152 MW, fully in service Sep 2016; built with a detachable pile-guide platform and floating-crane driving as the first deep-water monopiles without transition piece (CNR, 8 Sep 2016; CEEIA via Xinhua, 14 Sep 2016); the sources do not state outright that all 38 are monopiles.'),
    # ------------------------------------------------ 2026-10-03 補回的三座（出處原文已以 check_quotes 核對）
    F5('CHN', 'CTG Pingtan Waihai', 'jk', url='http://zrzyt.fj.gov.cn/zwgk/gsgg/202404/P020240429531356048270.pdf', sub='sb',
       zh='11 部試驗機組全用三樁導管架－吸力筒基礎（2022 年由四樁導管架改設計；福建省自然資源廳變更報告書）',
       en='All 11 test turbines stand on three-leg jackets on suction buckets (redesigned in 2022 from four-leg piled jackets; Fujian Department of Natural Resources change report)'),
    F5('CHN', 'Xiexin (GCL) Rudong H13', 'mp', url='https://www.sohu.com/a/494582778_121123888',
       zh='中交三航局施工：30 部 5 MW 風機的單樁基礎與一座 220 kV 海上升壓站', en='Built by CCCC Third Harbor: monopiles for the 30 × 5 MW turbines and a 220 kV offshore substation'),
    F5('CHN', 'Guoneng Gongxiang (Longyuan Nanri floating)', 'fl', url='http://www.sasac.gov.cn/n2588020/n2877938/n2879597/n30275940/c31096925/content.html', sub='semi',
       zh='三立柱半潛式平台（立柱間距 70 m、吃水 14 m），9 套吸力錨＋錨鏈繫泊，平台下方為養殖網箱',
       en='Three-column semi-submersible (70 m between columns, 14 m draught) moored by nine suction anchors with chains, with a fish cage below the platform'),
    # ------------------------------------------------ 2026-10-06 第 5 步續：中國 15 座（施工、完工或驗收紀錄；出處原文以 check_quotes 核對）
    F5('CHN', 'Huaneng Shantou Lemen (II)', 'mp', url='https://www.shantou.gov.cn/cnst/zwgk/jcxxgk/zdxm/content/post_2221327.html',
       zh='54 部 11 MW 全部為單樁：2023 年 1 月 12 日首根（7 號機位，長 94.3 m、直徑 8–9 m、1,802 t），5 月 22 日最後一根（#1，1,836 t、長 96.1 m）沉樁完成，「全部 54 根單樁基礎沉樁施工圓滿收官」（汕頭日報經汕頭市政府、南方＋）',
       en='All 54 × 11 MW turbines on monopiles: the first (position 7, 94.3 m long, 8–9 m in diameter, 1,802 t) was driven on 12 January 2023 and the last (#1, 1,836 t, 96.1 m) on 22 May 2023, completing “all 54 monopile foundations” (Shantou Daily via Shantou government; Nanfang+)'),
    F5('CHN', 'SPIC Jieyang Shenquan II', 'mp', url='https://www.spic.com.cn/spicm/xwzx/jcdt/202211/t20221121_320481.html',
       zh='50 部（16×8＋34×11 MW）全部為大直徑單樁：2022 年 11 月 17 日 50# 單樁（2,265 t、長 106 m）沉樁完成，全部 50 根單樁沉樁收官（國家電投廣東公司）',
       en='All 50 turbines (16 × 8 + 34 × 11 MW) on large-diameter monopiles: monopile no. 50 (2,265 t, 106 m) was driven on 17 November 2022, completing all 50 monopiles (SPIC Guangdong)'),
    F5('CHN', 'Huadian Yangjiang Qingzhou 3', 'jk', url='https://baijiahao.baidu.com/s?id=1697158371619334032&wfr=spider&for=pc',
       zh='67 部（37×6.8＋30×8.3 MW）用四樁套管（導管架）：設計方廣東院在首座套管吊裝時寫「風機基礎採用的是四樁導管架基礎」；一標段（中交海建）與另一施工總包（華西海工，44# 機位四根鋼管樁）都是四樁套管沉樁；2021 年 8 月已完成 38 個機位，2021 年 12 月 67 部全部併網（中國能建、世紀新能源網、陽江市生態環境局）',
       en='67 turbines (37 × 6.8 + 30 × 8.3 MW) on four-pile jackets: the designer GEDI wrote at the first jacket installation that “the turbine foundations are four-pile jackets”; piling reports from lot 1 (CCCC Haijian) and the other general contractor (Huaxi, four steel piles at position 44) both describe four-pile jackets; 38 positions piled by August 2021, all 67 connected by December 2021 (China Energy Engineering, ne21, Yangjiang Ecology & Environment Bureau)'),
    F5('CHN', 'Mingyang Yangjiang Qingzhou 4', 'jk', url='https://baijiahao.baidu.com/s?id=1768577370471170457&wfr=spider&for=pc',
       zh='44 部固定式（25×11＋19×12 MW）全部為套管（導管架）：廣州打撈局承建的 18 部 12 MW 導管架基礎 2023 年 6 月沉樁全部結束；龍源振華承攬的 25 部 11 MW 基礎由中信重工製作「導管架基礎及基礎鋼管樁」，2023 年 10 月完工；另一部是「導管架風機＋網箱」一體化裝備 MyAC-JS05；設計方廣東院稱項目採用風漁融合的一體化導管架設計（廣州日報、挖貝網、東方財富、人民網、中國能建）。明陽天成號浮式機組另列',
       en='All 44 fixed turbines (25 × 11 + 19 × 12 MW) on jackets: Guangzhou Salvage finished piling its 18 × 12 MW jacket foundations in June 2023; the 25 × 11 MW foundations built by Longyuan Zhenhua used “jacket foundations and pin piles” made by CITIC Heavy, completed in October 2023; one more unit is the MyAC-JS05 jacket-plus-net-cage installation; the designer GEDI describes an integrated jacket design (Guangzhou Daily, Wabei, Eastmoney, People’s Daily web, CEEC). The OceanX floating unit is recorded separately'),
    F5('CHN', 'SPIC Peninsula South V', 'mp', url='https://www.yantai.gov.cn/attach/0/dc27ca17fc004409b6428f4637afe946.pdf',
       zh='70 部 7 MW＋1 部 10 MW（F14 試驗樣機）全部為單樁：竣工環境保護驗收調查報告寫「風機基礎為單樁基礎結構」，7 MW 機位單樁約 1,000 t、直徑 7.0–8.4 m，10 MW 約 1,400 t（煙台市政府公開的驗收報告；2022 年 12 月全容量併網）',
       en='70 × 7 MW plus one 10 MW prototype (position F14), all on monopiles: the completion environmental acceptance report states the turbine foundations are monopiles, about 1,000 t and 7.0–8.4 m in diameter for the 7 MW units and about 1,400 t for the 10 MW unit (report published by Yantai city government; fully connected in December 2022)'),
    F5('CHN', 'Changle Waihai C', 'jk', url='https://www.ne21.com/news/show-157980.html',
       zh='全為套管（導管架），分兩種：吸力式套管（紫金鋼管 2021 年 2 月首套出港時寫全場計畫布置 49 台）與四樁套管；惠生海工交付長樂外海 A、C 區共 11 座三筒吸力樁套管時寫「項目採用四樁導管架及三筒吸力樁導管架基礎」（2021-10）；各種型式的實際座數未查到',
       en='All jackets, of two kinds: suction-bucket jackets (49 planned, per Zijin when the first one sailed in February 2021) and four-pile jackets; Wison, delivering 11 three-bucket suction jackets for Changle areas A and C, says the projects use “four-pile jackets and three-bucket suction jackets” (October 2021); the as-built count of each kind was not found'),
    F5('CHN', 'SPIC Jieyang Shenquan I', 'mp', url='http://baijiahao.baidu.com/s?id=1710037058952715402&wfr=spider&for=pc',
       zh='一期 53 部（16×7＋37×5.5 MW，Ⅰ、Ⅱ標段）2021 年 9 月 4 日「53 根單樁全部完成沉樁」（廣州日報）；二期 13 部 7 MW 2022 年 7 月 20 日最後一根單樁完成，全部單樁沉樁收官（國家電投廣東公司、揭陽日報）；共 66 部全部為單樁',
       en='Phase 1, 53 turbines (16 × 7 + 37 × 5.5 MW, lots I and II): “all 53 monopiles driven” on 4 September 2021 (Guangzhou Daily); phase 2, 13 × 7 MW: the last monopile was driven on 20 July 2022, completing all its monopiles (SPIC Guangdong, Jieyang Daily); all 66 turbines on monopiles'),
    F5('CHN', 'SPIC Rudong H4', 'mp', url='http://baijiahao.baidu.com/s?id=1717138738488605970&wfr=spider&for=pc',
       zh='100 部 4 MW 風機各一根單樁：2021 年 10 月 24 日 H4 的 100 根基礎樁全部沉樁完成（國際能源網風電日報，2021-11）；國電投南通新能源 2026 年 7 月的運維報導寫「如東 H4、H7 海上風電項目單樁基礎及附屬構件腐蝕修復」（中國日報網）',
       en='100 × 4 MW turbines, one monopile each: all 100 foundation piles at H4 were driven by 24 October 2021 (in-en.com wind daily, Nov 2021); a July 2026 O&M report by SPIC Nantong New Energy describes corrosion repair of the “monopile foundations and appurtenances” of Rudong H4 and H7 (China Daily web)'),
    F5('CHN', 'SPIC Rudong H7', 'mp', url='http://baijiahao.baidu.com/s?id=1717138738488605970&wfr=spider&for=pc',
       zh='100 部 4 MW 風機各一根單樁：2021 年 11 月 18 日最後一根（67 號）單樁沉樁完成，H7 的 100 根鋼管樁全部完成（國際能源網風電日報）；國電投南通新能源 2026 年 7 月的運維報導寫「如東 H4、H7 海上風電項目單樁基礎及附屬構件腐蝕修復」（中國日報網）',
       en='100 × 4 MW turbines, one monopile each: the last monopile (no. 67) was driven on 18 November 2021, completing all 100 steel piles of H7 (in-en.com wind daily); a July 2026 O&M report by SPIC Nantong New Energy describes corrosion repair of the “monopile foundations” of Rudong H4 and H7 (China Daily web)'),
    F5('CHN', 'Zhejiang Shengsi 2 Offshore wind farm', 'mx', url='https://www.hunningtu.com/h-nd-5670.html', parts=[["pc", 31], ["mp", 32]],
       zh='63 個機位分兩種基礎：中交三航局 31 個機位為承台（30 座高樁承台＋首樁機位 1 座混凝土承台，2021 年 8 月全部澆築完成）；中鐵大橋局 32 個機位為直徑 6–8.5 m 的大直徑單樁（B 標段 2021 年 7 月 31 日沉樁全部完成）；31 部明陽 6.45 MW＋32 部上海電氣 6.25 MW，共 399.95 MW（中國混凝土網、世紀新能源網）',
       en='63 positions on two foundation types: CCCC Third Harbour’s 31 positions have pile caps (30 high-rise pile caps plus one concrete cap at the first-pile position, all poured by August 2021); CRBBG’s 32 positions are 6–8.5 m monopiles (lot B piling finished on 31 July 2021); 31 Mingyang 6.45 MW + 32 Shanghai Electric 6.25 MW, 399.95 MW in all (hunningtu.com, ne21)'),
    F5('CHN', 'Jiangsu Dongtai Zhugensha H2 Offshore wind farm', 'mp', url='https://www.ne21.com/news/show-154803.html',
       zh='67 部（50×4.0＋17×6.0 MW）：EPC 總承包華東院 2020 年 12 月的年終報導列出「全部單樁沉樁完成」等節點，67 部風機年底前全部安裝完成；未見其他基礎型式的紀錄（只有這一個出處寫明型式）',
       en='67 turbines (50 × 4.0 + 17 × 6.0 MW): the EPC contractor HDEC’s year-end report (December 2020) lists “all monopile piling completed” among the milestones, with all 67 turbines installed by the end of 2020; no other foundation type is mentioned (this is the only source that names the type)'),
    F5('CHN', 'SPIC Peninsula South 3', 'mp', url='https://www.ne21.com/news/show-167096.html',
       zh='58 部 5.2 MW 全部為鋼管單樁（平均樁重 977 t、樁長 86.4 m）；2021 年 11 月 7 日完成 58 根單樁沉樁，12 月 16 日全容量併網（世紀新能源網轉載國家電投與華電重工報導）',
       en='All 58 × 5.2 MW turbines on steel monopiles (977 t and 86.4 m on average); all 58 monopiles driven by 7 November 2021, fully connected on 16 December 2021 (ne21 reposts of SPIC and Huadian Heavy Industries)'),
    F5('CHN', 'Huaneng Peninsula South 4', 'mp', url='http://baijiahao.baidu.com/s?id=1718564409194432714&wfr=spider&for=pc',
       zh='58 部 5.2 MW 全部為單樁：最後一根單樁（58 號鋼管樁，長 97 m、直徑 7.7 m、重 1,304 t）2021 年 11 月打設完成，「國內單樁基礎水深最深的大型海上風電場之一」；2021 年 12 月 10 日 58 部全部併網（中國發展網、華能國際經中證網）',
       en='All 58 × 5.2 MW turbines on monopiles: the last monopile (pile 58, 97 m long, 7.7 m in diameter, 1,304 t) was driven in November 2021, “one of China’s large offshore farms with monopiles in the deepest water”; all 58 connected on 10 December 2021 (China Development Net; Huaneng Power International via cs.com.cn)'),
    F5('CHN', 'Zhejiang Jiaxing 2 Offshore wind farm', 'mx', url='https://www.ne21.com/news/show-135810.html', parts=[["mp", 36], ["pc", 14]],
       zh='50 部 6 MW：Ⅰ標段（中交三航局）25 個機位＝11 座單樁＋14 座高樁承台，單樁 2020 年 11 月全部沉樁完成，25 部 2021 年 8 月全部完成；Ⅱ標段（中鐵大橋局）25 部為直徑 6.5–7.5 m 的大直徑單樁，2021 年 11 月全部安裝完成；合計 36 座單樁、14 座高樁承台（世紀新能源網、金山海事、工人日報）',
       en='50 × 6 MW: lot I (CCCC Third Harbour), 25 positions = 11 monopiles + 14 high-rise pile caps, monopiles all driven by November 2020 and all 25 turbines completed by August 2021; lot II (CRBBG), 25 turbines on 6.5–7.5 m monopiles, all installed by November 2021; 36 monopiles and 14 pile caps in all (ne21, Jinshan MSA, Workers’ Daily)'),
    F5('CHN', 'Shanghai Fengxian', 'mp', url='https://baijiahao.baidu.com/s?id=1745202495282786887&wfr=spider&for=pc',
       zh='32 部 6.45 MW 全部為無過渡段單樁：中交三航局「1~32 風力發電機組工程」獲 2020–2021 年度上海市優質工程，報導寫「風電機組基礎採用無過渡段單樁基礎型式」；業主上海電力稱本案是上海周邊海域首次應用單樁基礎的海上風電項目（2021 年 12 月 28 日全部併網）',
       en='All 32 × 6.45 MW turbines on monopiles without transition pieces: CCCC Third Harbour’s “wind turbines 1–32” works won a 2020–21 Shanghai quality award, whose citation says the turbine foundations are TP-less monopiles; the owner Shanghai Electric Power calls it the first offshore farm near Shanghai to use monopiles (all connected on 28 December 2021)'),
    # ------------------------------------------------ 歐洲早期示範風場（已除役；出處原文以 check_quotes 核對）· early European pilots, decommissioned
    F('DNK', 'Vindeby', 'gb', url='https://www.windpowermonthly.com/article/1427436/dong-begins-vindeby-decommissioning-pictures',
      zh='世界第一座離岸風場：11 部 450 kW 坐在混凝土重力式基礎上（Ørsted 稱基礎以燈塔基礎為本，澆灌後浮運到場填砂）；2017 年 9 月拆除完畢',
      en='The world’s first offshore wind farm: 11 × 450 kW on concrete gravity-base foundations (Ørsted says they were modelled on a lighthouse foundation, floated out and filled with sand); removal completed in September 2017'),
    F('GBR', 'Beatrice Demonstrator', 'jk', url='https://en.wikipedia.org/wiki/Beatrice_Wind_Farm',
      zh='2 部 5 MW 示範機立在四腳套管上（每座用四根 1.8 m 樁固定，水深約 45 m，2007 年）；油田 2015 年停產，示範機預定 2024 至 2027 年間除役',
      en='The two 5 MW demonstrator turbines stand on four-leg jackets (each fixed by four 1.8 m piles in about 45 m of water, 2007); the oil field closed in 2015 and the demonstrator is to be decommissioned between 2024 and 2027'),
    F('NLD', 'Lely (Medemblik)', 'mp', url='https://www.offshorewind.biz/2016/12/07/lely-wind-farm-fully-decommissioned-video/',
      zh='荷蘭第一座離岸風場：4 部 500 kW 各立在一根單樁上（樁長 26 m、直徑 3.2–3.7 m）；2016 年底以振動錘整根拔除',
      en='The Netherlands’ first offshore wind farm: 4 × 500 kW, each on a monopile (26 m long, 3.2–3.7 m in diameter); the piles were vibrated out whole at the end of 2016'),
    F('SWE', 'Yttre Stengrund', 'mp', url='https://www.windpowermonthly.com/article/1375616/yttre-stengrund-decommissioning-begins',
      zh='5 部 2 MW 立在單樁上；2015 年 11 月除役，單樁切至海床面（Windpower Monthly）。2006 年的潛水調查（Wilhelmsson 等）與瑞典環保署報告也寫鋼製單樁；'
         'Vattenfall 2016 年新聞稿說「把混凝土基礎切至海床面」，應指單樁裡的灌漿或混凝土填充，不改型式',
      en='5 × 2 MW on monopiles; decommissioned in November 2015 with the monopiles cut down to seabed level (Windpower Monthly). A 2006 diver survey (Wilhelmsson et al.) '
         'and a Swedish EPA report also describe steel monopiles; Vattenfall’s 2016 release about cutting “the concrete foundations” presumably means the grout or concrete fill of the piles, so the type is unchanged'),
    F4('USA', 'Empire wind farm', 'mp', url='https://www.empirewind.com/offshore-installation/',
       zh='54 座單樁（Sif 製）配轉接段，2025 年夏秋安裝（海上變電站立在套管上）',
       en='54 monopiles (made by Sif) with transition pieces, installed in summer and autumn 2025 (the offshore substation stands on a jacket)'),
    F4('USA', 'Sunrise Wind', 'mp', url='https://orsted.com/en/media/news/2026/01/sunrise-wind-llc-to-file-preliminary-injunction-ag-1474210611',
       zh='84 座風機單樁（2025 年年中開始安裝，2026 年 8 月已裝好 77 座）；海上變流站另為一座構造',
       en='84 turbine monopiles (installation started in mid-2025; 77 were in place by August 2026); the offshore converter station is a separate structure'),
]

# OSPAR 有紀錄、但這一步刻意不列的風場（理由寫在報告裡，之後的步驟再查）
EXCLUDED = [
    ('DNK', 'Frederikshavn', ['DK03'],
     '試驗場：丹麥能源署記載 2003 年在海上設 3 部（7.6 MW），港口擴建後兩部已在陸地上、海上只剩 1 部 2.3 MW，但沒寫是哪一部；'
     '各機組的基礎不同（其中一部 V90 用吸力桶試驗基礎），OSPAR 寫全為單樁、14 MW 也對不上，先不列',
     'A test site: the Danish Energy Agency records 3 turbines at sea from 2003 (7.6 MW); after the harbour was extended two now stand on land '
     'and only one 2.3 MW turbine is left at sea, but it does not say which; the turbines had different foundations (one V90 on a trial '
     'suction bucket), and OSPAR’s “all monopiles” and 14 MW do not match, so it is left out'),
    # 第 4 步（2026-09）
    ('JPN', 'Eurus Akita Port semi-offshore', [],
     'JWPA 另計為「セミ洋上」的 1 部 3 MW：ユーラス秋田港ウインドファーム（6 部 3 MW，2015 年 2 月運轉）中立在水中的那一部；'
     '查不到業主、施工廠商、NEDO、國土交通省或 JWPA 的文件寫出它的基礎型式',
     'The single 3 MW unit that JWPA counts as “semi-offshore”: the one turbine standing in the water at Eurus Akita Port Wind Farm '
     '(six 3 MW turbines, operating since February 2015); no document from the owner, the contractors, NEDO, MLIT or JWPA was found '
     'that gives its foundation type'),
    ('KOR', 'Yeonggwang Wind offshore wind farm', [],
     '靈光風電陸海混合風場（35 部、79.6 MW）中立在潮間帶的 15 部 2.3 MW，退潮時周圍是灘地；'
     '查不到開發商、施工廠商或政府文件寫出這 15 部的基礎型式',
     'The 15 × 2.3 MW turbines of the Yeonggwang Wind onshore-and-offshore complex (35 turbines, 79.6 MW) that stand in the intertidal '
     'zone, dry at low tide; no developer, contractor or government statement of their foundation type was found'),
]
